/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jnflsicUI;

import java.awt.Toolkit;
import javax.swing.JOptionPane;
import jnflsicCourseDataProcess.Course;
import jnflsicCourseDatabase.CourseData;

/**
 *
 * @author shen
 */
public class AddCourseForm extends javax.swing.JFrame {

    /**
     * Creates new form AddStudentForm
     */
    public AddCourseForm() {
        initComponents();
        setDepartmentList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelFirstName = new javax.swing.JLabel();
        jLabelLastName1 = new javax.swing.JLabel();
        jLabelPhone = new javax.swing.JLabel();
        jTextFieldCourseName = new javax.swing.JTextField();
        jScrollPanelAddress = new javax.swing.JScrollPane();
        jTextDepDescription = new javax.swing.JTextArea();
        jButtonAddCourse = new javax.swing.JButton();
        jButtonCourseCancel = new javax.swing.JButton();
        jButtonResetCourse = new javax.swing.JButton();
        jLabelLastName2 = new javax.swing.JLabel();
        jTextFieldPrerequirement = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabelPhone1 = new javax.swing.JLabel();
        jLabelPhone2 = new javax.swing.JLabel();
        jLabelPhone3 = new javax.swing.JLabel();
        jComboBoxDepartment = new javax.swing.JComboBox();
        jComboBoxArea = new javax.swing.JComboBox();
        jCheckBoxCourseActive = new javax.swing.JCheckBox();
        jComboBoxCredit = new javax.swing.JComboBox();
        jLabelPhone4 = new javax.swing.JLabel();
        jComboBoxTeacher = new javax.swing.JComboBox();
        jLabelPhone5 = new javax.swing.JLabel();
        jTextFieldMaxStu = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("New Course");

        jLabelFirstName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelFirstName.setText("Course Name:");

        jLabelLastName1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelLastName1.setText("Course Description:");

        jLabelPhone.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPhone.setText("Course Active:");

        jTextFieldCourseName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextDepDescription.setColumns(20);
        jTextDepDescription.setRows(5);
        jScrollPanelAddress.setViewportView(jTextDepDescription);

        jButtonAddCourse.setText("Add");
        jButtonAddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCourseActionPerformed(evt);
            }
        });

        jButtonCourseCancel.setText("Cancel");
        jButtonCourseCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCourseCancelActionPerformed(evt);
            }
        });

        jButtonResetCourse.setText("Reset");
        jButtonResetCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetCourseActionPerformed(evt);
            }
        });

        jLabelLastName2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelLastName2.setText("Course Prerequirement:");

        jTextFieldPrerequirement.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("*");

        jLabelPhone1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPhone1.setText("Course Credit:");

        jLabelPhone2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPhone2.setText("Course Area:");

        jLabelPhone3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPhone3.setText("Course Department:");

        jComboBoxDepartment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A" }));
        jComboBoxDepartment.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxDepartmentItemStateChanged(evt);
            }
        });
        jComboBoxDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDepartmentActionPerformed(evt);
            }
        });

        jComboBoxArea.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "Advanced Placement (AP)", "Advanced Level (AL)", "Advanced Subsidiary Level (AS)", "National Course", "Second Language", "Others" }));

        jCheckBoxCourseActive.setText("Active");

        jComboBoxCredit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabelPhone4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPhone4.setText("Teacher:");

        jComboBoxTeacher.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "1" }));
        jComboBoxTeacher.setEnabled(false);

        jLabelPhone5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPhone5.setText("Course Max Number Of Student:");

        jTextFieldMaxStu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMaxStuKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelFirstName)
                            .addComponent(jLabelLastName1)
                            .addComponent(jLabelPhone)
                            .addComponent(jLabelLastName2)
                            .addComponent(jLabelPhone1)
                            .addComponent(jLabelPhone2)
                            .addComponent(jLabelPhone3)
                            .addComponent(jLabelPhone4)
                            .addComponent(jLabelPhone5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCourseName)
                            .addComponent(jScrollPanelAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(jTextFieldPrerequirement)
                            .addComponent(jComboBoxDepartment, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxArea, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxCredit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxTeacher, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckBoxCourseActive)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextFieldMaxStu)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAddCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonResetCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButtonCourseCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFirstName)
                    .addComponent(jTextFieldCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPhone)
                    .addComponent(jCheckBoxCourseActive))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPhone1)
                    .addComponent(jComboBoxCredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPhone2)
                    .addComponent(jComboBoxArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPhone5)
                    .addComponent(jTextFieldMaxStu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPhone3)
                    .addComponent(jComboBoxDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPhone4)
                    .addComponent(jComboBoxTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLastName2)
                    .addComponent(jTextFieldPrerequirement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPanelAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLastName1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCourseCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonResetCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonResetCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetCourseActionPerformed
        clear();
    }//GEN-LAST:event_jButtonResetCourseActionPerformed
    
    private void clear(){
        jTextFieldCourseName.setText("");
        jCheckBoxCourseActive.setSelected(false);
        jComboBoxCredit.setSelectedIndex(0);
        jComboBoxArea.setSelectedIndex(0);
        jComboBoxDepartment.setSelectedIndex(0);
        jTextFieldPrerequirement.setText("");
        jTextDepDescription.setText("");
        jTextFieldMaxStu.setText("");
    }
    
    private void jButtonCourseCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCourseCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCourseCancelActionPerformed
    
    private boolean verify(){
        if(jTextFieldCourseName.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter Department Name");
            jTextFieldCourseName.requestFocus();
            return false;
        }
        return true;
    }
    
    private void jButtonAddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCourseActionPerformed
        String courseName = jTextFieldCourseName.getText();        
        String Prerequirement = jTextFieldPrerequirement.getText();
        String description = jTextDepDescription.getText();
        boolean active = jCheckBoxCourseActive.isSelected();
        int credit = jComboBoxCredit.getSelectedIndex()+1;
        String area = jComboBoxArea.getSelectedItem().toString();      
        String department = jComboBoxDepartment.getSelectedItem().toString();
        String teacher = jComboBoxTeacher.getSelectedItem().toString();
        String strMaxStudent = jTextFieldMaxStu.getText();
        int maxStudent = 0;
        if(!(strMaxStudent.equals(""))&&(strMaxStudent!=null)){
            maxStudent = Integer.parseInt(strMaxStudent);
        }
        int teacherID = -1;
        int departmentID = -1;

        if(!verify()){
            return;
        }
        //String Name, String pReq, String des, boolean act, String c, String a, String depart
        Course cos = new Course(courseName, Prerequirement, description, active, credit, area, department, teacher, maxStudent);
        
        if(!department.equals("N/A")){
            departmentID = cos.getDepartmentID();
        }
        
        cos.setDepartmentID(departmentID);
        
        if(!teacher.equals("N/A")){
            teacherID = cos.getTeacherID();
        }
        cos.setTeacherID(teacherID);
        
        if(Course.operateData('i', cos)){
            if(ManageCourseForm.tableExist()){
                ManageCourseForm.resetTable();
            }
            clear();
        }
    }//GEN-LAST:event_jButtonAddCourseActionPerformed

    private void jComboBoxDepartmentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxDepartmentItemStateChanged
//        if(!jComboBoxDepartment.getSelectedItem().toString().equals("N/A")){
//            jComboBoxTeacher.setEnabled(true);
//            setTeacherList();
//        }else{
//            jComboBoxTeacher.setEnabled(false);
//            jComboBoxTeacher.setSelectedIndex(0);
//        }
    }//GEN-LAST:event_jComboBoxDepartmentItemStateChanged

    private void jComboBoxDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDepartmentActionPerformed
        if(!jComboBoxDepartment.getSelectedItem().toString().equals("N/A")){
            jComboBoxTeacher.setEnabled(true);
            setTeacherList();
        }else{
            jComboBoxTeacher.setEnabled(false);
            jComboBoxTeacher.setSelectedIndex(0);
            jComboBoxTeacher.removeAllItems();
            jComboBoxTeacher.addItem("N/A");
        }
    }//GEN-LAST:event_jComboBoxDepartmentActionPerformed

    private void jTextFieldMaxStuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMaxStuKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldMaxStuKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddCourseForm st = new AddCourseForm();
                //JComboBox bo = new JComboBox();

                
                st.middleScreen();
                //st.dispose();
                //st.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                //st.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                st.setVisible(true);
            }
        });
    }
    
    private void setTeacherList(){
        jComboBoxTeacher.removeAllItems();
        jComboBoxTeacher.addItem("N/A");
        if(!jComboBoxDepartment.getSelectedItem().toString().equals("N/A")){
            String[] teaList = CourseData.teacherList(jComboBoxDepartment.getSelectedItem().toString());
            for(int i = 0; i<teaList.length; i++){
                jComboBoxTeacher.addItem(teaList[i]);
            }
        }
    }
    
    private void setDepartmentList(){
        String[] departmentList = CourseData.getDepartmentList();
        for(int i = 0; i<departmentList.length; i++){
            jComboBoxDepartment.addItem(departmentList[i]);
        }
    }
    
    private void middleScreen(){
        double width = Toolkit.getDefaultToolkit().getScreenSize().getWidth();
        double height = Toolkit.getDefaultToolkit().getScreenSize().getHeight();
        this.setLocation( (int) (width - this.getWidth()) / 2,(int) (height - this.getHeight()) / 2);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddCourse;
    private javax.swing.JButton jButtonCourseCancel;
    private javax.swing.JButton jButtonResetCourse;
    private javax.swing.JCheckBox jCheckBoxCourseActive;
    private javax.swing.JComboBox jComboBoxArea;
    private javax.swing.JComboBox jComboBoxCredit;
    private javax.swing.JComboBox jComboBoxDepartment;
    private javax.swing.JComboBox jComboBoxTeacher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFirstName;
    private javax.swing.JLabel jLabelLastName1;
    private javax.swing.JLabel jLabelLastName2;
    private javax.swing.JLabel jLabelPhone;
    private javax.swing.JLabel jLabelPhone1;
    private javax.swing.JLabel jLabelPhone2;
    private javax.swing.JLabel jLabelPhone3;
    private javax.swing.JLabel jLabelPhone4;
    private javax.swing.JLabel jLabelPhone5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPanelAddress;
    private javax.swing.JTextArea jTextDepDescription;
    private javax.swing.JTextField jTextFieldCourseName;
    private javax.swing.JTextField jTextFieldMaxStu;
    private javax.swing.JTextField jTextFieldPrerequirement;
    // End of variables declaration//GEN-END:variables
}
