/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jnflsicUI;

import java.awt.Toolkit;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import jnflsicDataProcess.Student;

/**
 *
 * @author shen
 */
public class AddStudentForm extends javax.swing.JFrame {

    /**
     * Creates new form AddStudentForm
     */
    public AddStudentForm() {
        initComponents();
        ButtonGroup bg = new ButtonGroup();
        bg.add(jRadioButtonMan);
        bg.add(jRadioButtonfelmale);
        jRadioButtonMan.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelFirstName = new javax.swing.JLabel();
        jLabelLastName = new javax.swing.JLabel();
        jLabelLastName1 = new javax.swing.JLabel();
        jLabelSex = new javax.swing.JLabel();
        jLabelBirthdate = new javax.swing.JLabel();
        jLabelPhone = new javax.swing.JLabel();
        jLabelAddress = new javax.swing.JLabel();
        jTextFieldFirstName = new javax.swing.JTextField();
        jTextFieldMiddleName = new javax.swing.JTextField();
        jTextFieldLastName = new javax.swing.JTextField();
        jRadioButtonMan = new javax.swing.JRadioButton();
        jRadioButtonfelmale = new javax.swing.JRadioButton();
        dateChooserCombo = new datechooser.beans.DateChooserCombo();
        jTextFieldPhone = new javax.swing.JTextField();
        jScrollPanelAddress = new javax.swing.JScrollPane();
        jTextAreaAddress = new javax.swing.JTextArea();
        jButtonAddStudent = new javax.swing.JButton();
        jButtonStuCancel = new javax.swing.JButton();
        jButtonResetStu = new javax.swing.JButton();
        jLabelSex1 = new javax.swing.JLabel();
        jComboBoxGrade = new javax.swing.JComboBox();
        jLabelBirthdate1 = new javax.swing.JLabel();
        jTextFieldEnrollYear = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("New Student");

        jLabelFirstName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelFirstName.setText("First Name:");

        jLabelLastName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelLastName.setText("Last Name:");

        jLabelLastName1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelLastName1.setText("Middle Name:");

        jLabelSex.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelSex.setText("Sex:");

        jLabelBirthdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelBirthdate.setText("BirthDate:");

        jLabelPhone.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPhone.setText("Phone:");

        jLabelAddress.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelAddress.setText("Address:");

        jTextFieldFirstName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextFieldMiddleName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextFieldLastName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jRadioButtonMan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButtonMan.setSelected(true);
        jRadioButtonMan.setText("Male");

        jRadioButtonfelmale.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButtonfelmale.setText("Female");

        dateChooserCombo.setCalendarPreferredSize(new java.awt.Dimension(400, 350));
        dateChooserCombo.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.BOLD, 12));
        dateChooserCombo.setNavigateFont(new java.awt.Font("Shonar Bangla", java.awt.Font.PLAIN, 9));

        jTextFieldPhone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPhoneKeyTyped(evt);
            }
        });

        jTextAreaAddress.setColumns(20);
        jTextAreaAddress.setRows(5);
        jScrollPanelAddress.setViewportView(jTextAreaAddress);

        jButtonAddStudent.setText("Add");
        jButtonAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddStudentActionPerformed(evt);
            }
        });

        jButtonStuCancel.setText("Cancel");
        jButtonStuCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStuCancelActionPerformed(evt);
            }
        });

        jButtonResetStu.setText("Reset");
        jButtonResetStu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetStuActionPerformed(evt);
            }
        });

        jLabelSex1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelSex1.setText("Grade:");

        jComboBoxGrade.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBoxGrade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10", "11", "12" }));

        jLabelBirthdate1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelBirthdate1.setText("Enrolled Year:");

        jTextFieldEnrollYear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldEnrollYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEnrollYearKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelLastName1)
                                        .addComponent(jLabelFirstName, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabelLastName)
                                    .addComponent(jLabelSex)
                                    .addComponent(jLabelBirthdate)
                                    .addComponent(jLabelSex1)
                                    .addComponent(jLabelBirthdate1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldFirstName)
                                    .addComponent(jTextFieldMiddleName)
                                    .addComponent(jTextFieldLastName)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jRadioButtonMan)
                                                .addGap(28, 28, 28)
                                                .addComponent(jRadioButtonfelmale))
                                            .addComponent(jComboBoxGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTextFieldEnrollYear, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dateChooserCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelPhone)
                                    .addComponent(jLabelAddress))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonAddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonResetStu, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonStuCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPanelAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextFieldPhone))))))))
                .addGap(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFirstName)
                    .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLastName1)
                    .addComponent(jTextFieldMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLastName))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSex)
                    .addComponent(jRadioButtonMan)
                    .addComponent(jRadioButtonfelmale))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSex1)
                    .addComponent(jComboBoxGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBirthdate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateChooserCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBirthdate1)
                    .addComponent(jTextFieldEnrollYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelPhone)
                        .addGap(16, 16, 16)
                        .addComponent(jLabelAddress)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPanelAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonStuCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonResetStu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonResetStuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetStuActionPerformed
        clear();
    }//GEN-LAST:event_jButtonResetStuActionPerformed
    
    private void clear(){
        jTextFieldFirstName.setText("");
        jTextFieldMiddleName.setText("");
        jTextFieldLastName.setText("");
        jRadioButtonMan.setSelected(true);
        jRadioButtonfelmale.setSelected(false);
        Calendar cal1 = Calendar.getInstance();
        cal1.setTime(new Date());
        dateChooserCombo.setSelectedDate(cal1);
        jTextFieldPhone.setText("");
        jTextAreaAddress.setText("");
        jTextFieldEnrollYear.setText("");
        jComboBoxGrade.setSelectedIndex(0);
    }
    
    private void jButtonStuCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStuCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonStuCancelActionPerformed

    private void jTextFieldPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPhoneKeyTyped
        //allow only numbers
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldPhoneKeyTyped
    
    private boolean verify(){
        if(jTextFieldFirstName.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter First Name");
            jTextFieldFirstName.requestFocus();
            return false;
        }
        if(jTextFieldLastName.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter Last Name");
            jTextFieldLastName.requestFocus();
            return false;
        }
        if(dateChooserCombo.getSelectedDate()==null){
            JOptionPane.showMessageDialog(null, "Please enter select a date");
            dateChooserCombo.requestFocus();
            return false;
        }
        if(jTextFieldEnrollYear.getText().equals("")||jTextFieldEnrollYear.getText().length()!=4){
            JOptionPane.showMessageDialog(null, "Please enter enroll year");
            jTextFieldEnrollYear.requestFocus();
            return false;
        }
        
        Date now = new Date();
        Calendar n = Calendar.getInstance();
        n.setTime(now);
        int nY = n.get(Calendar.YEAR);
        if(nY-Integer.parseInt(jTextFieldEnrollYear.getText())<0){
            JOptionPane.showMessageDialog(null, "Please enter corrected enroll year");
            jTextFieldEnrollYear.requestFocus();
            return false;
        }
        
        
        if(dateChooserCombo.getSelectedDate().getTime().compareTo(new Date())>0){
            JOptionPane.showMessageDialog(null, "No Student from future are allowed");
            dateChooserCombo.requestFocus();
            return false;
        }
        if(jTextAreaAddress.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter a home address");
            jTextAreaAddress.requestFocus();
            return false;
        }
        return true;
    }
    
    private void jButtonAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddStudentActionPerformed
        String fN = jTextFieldFirstName.getText();
        String mN = jTextFieldMiddleName.getText();
        String lN = jTextFieldLastName.getText();
        char sex = 'm';
        if(jRadioButtonfelmale.isSelected()){
            sex = 'f';
        }
        int grade = jComboBoxGrade.getSelectedIndex()+10;
        Calendar bd = dateChooserCombo.getSelectedDate();
        int year = Integer.parseInt(jTextFieldEnrollYear.getText());
        String pNum = jTextFieldPhone.getText();
        String add = jTextAreaAddress.getText();
        //String firstName, String middleName, String lastName, char sex, int grade, Calendar birthday, int year, String phoneNum, String add

        if(!verify()){
            return;
        }
        Student st = new Student(fN,mN,lN,sex,grade,bd,year,pNum,add);
        if(Student.operateData('i', st)){
            ManageStudentForm.resetTable();
            clear();
        }
    }//GEN-LAST:event_jButtonAddStudentActionPerformed

    private void jTextFieldEnrollYearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEnrollYearKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldEnrollYearKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddStudentForm st = new AddStudentForm();
                st.middleScreen();
                //st.dispose();
                //st.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                //st.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                st.setVisible(true);
            }
        });
    }
    
    private void middleScreen(){
        double width = Toolkit.getDefaultToolkit().getScreenSize().getWidth();
        double height = Toolkit.getDefaultToolkit().getScreenSize().getHeight();
        this.setLocation( (int) (width - this.getWidth()) / 2,(int) (height - this.getHeight()) / 2);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserCombo;
    private javax.swing.JButton jButtonAddStudent;
    private javax.swing.JButton jButtonResetStu;
    private javax.swing.JButton jButtonStuCancel;
    private javax.swing.JComboBox jComboBoxGrade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelBirthdate;
    private javax.swing.JLabel jLabelBirthdate1;
    private javax.swing.JLabel jLabelFirstName;
    private javax.swing.JLabel jLabelLastName;
    private javax.swing.JLabel jLabelLastName1;
    private javax.swing.JLabel jLabelPhone;
    private javax.swing.JLabel jLabelSex;
    private javax.swing.JLabel jLabelSex1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonMan;
    private javax.swing.JRadioButton jRadioButtonfelmale;
    private javax.swing.JScrollPane jScrollPanelAddress;
    private javax.swing.JTextArea jTextAreaAddress;
    private javax.swing.JTextField jTextFieldEnrollYear;
    private javax.swing.JTextField jTextFieldFirstName;
    private javax.swing.JTextField jTextFieldLastName;
    private javax.swing.JTextField jTextFieldMiddleName;
    private javax.swing.JTextField jTextFieldPhone;
    // End of variables declaration//GEN-END:variables
}
