/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jnflsicUI;

import jnflsicTeacherDataProcess.Teacher;
import java.awt.Toolkit;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import jnflsicDataProcess.Student;
import jnflsicTeacherDatabase.teacherData;

/**
 *
 * @author shen
 */
public class AddTeacherForm extends javax.swing.JFrame {

    /**
     * Creates new form AddStudentForm
     */
    public AddTeacherForm() {
        initComponents();
        setDepartmentList();
        ButtonGroup bg = new ButtonGroup();
        bg.add(jRadioButtonMan);
        bg.add(jRadioButtonfelmale);
        jRadioButtonMan.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelFirstName = new javax.swing.JLabel();
        jLabelLastName = new javax.swing.JLabel();
        jLabelLastName1 = new javax.swing.JLabel();
        jLabelSex = new javax.swing.JLabel();
        jLabelBirthdate = new javax.swing.JLabel();
        jLabelPhone = new javax.swing.JLabel();
        jTextFieldFirstName = new javax.swing.JTextField();
        jTextFieldMiddleName = new javax.swing.JTextField();
        jTextFieldLastName = new javax.swing.JTextField();
        jRadioButtonMan = new javax.swing.JRadioButton();
        jRadioButtonfelmale = new javax.swing.JRadioButton();
        dateChooserCombo = new datechooser.beans.DateChooserCombo();
        jTextFieldPhone = new javax.swing.JTextField();
        jButtonAddStudent = new javax.swing.JButton();
        jButtonStuCancel = new javax.swing.JButton();
        jButtonResetStu = new javax.swing.JButton();
        jLabelSex1 = new javax.swing.JLabel();
        jComboBoxPosition = new javax.swing.JComboBox();
        jLabelBirthdate1 = new javax.swing.JLabel();
        jTextFieldGraduSchool = new javax.swing.JTextField();
        jLabelFirstName1 = new javax.swing.JLabel();
        jLabelLastName2 = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jLabelLastName3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jCheckBoxValid = new javax.swing.JCheckBox();
        jLabelLastName4 = new javax.swing.JLabel();
        jCheckBoxHasTeaCert = new javax.swing.JCheckBox();
        jLabelLastName5 = new javax.swing.JLabel();
        jTextFieldDegree = new javax.swing.JTextField();
        jTextFieldMajor = new javax.swing.JTextField();
        jComboBoxDepartment = new javax.swing.JComboBox();
        jLabelSex2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("New Teacher");

        jLabelFirstName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelFirstName.setText("First Name:");

        jLabelLastName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelLastName.setText("Last Name:");

        jLabelLastName1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelLastName1.setText("Middle Name:");

        jLabelSex.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelSex.setText("Sex:");

        jLabelBirthdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelBirthdate.setText("BirthDate:");

        jLabelPhone.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPhone.setText("Phone:");

        jTextFieldFirstName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextFieldMiddleName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextFieldLastName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jRadioButtonMan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButtonMan.setSelected(true);
        jRadioButtonMan.setText("Male");

        jRadioButtonfelmale.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButtonfelmale.setText("Female");

        dateChooserCombo.setCalendarPreferredSize(new java.awt.Dimension(400, 350));
        dateChooserCombo.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.BOLD, 12));
        dateChooserCombo.setNavigateFont(new java.awt.Font("Shonar Bangla", java.awt.Font.PLAIN, 9));

        jTextFieldPhone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPhoneKeyTyped(evt);
            }
        });

        jButtonAddStudent.setText("Add");
        jButtonAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddStudentActionPerformed(evt);
            }
        });

        jButtonStuCancel.setText("Cancel");
        jButtonStuCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStuCancelActionPerformed(evt);
            }
        });

        jButtonResetStu.setText("Reset");
        jButtonResetStu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetStuActionPerformed(evt);
            }
        });

        jLabelSex1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelSex1.setText("Position:");

        jComboBoxPosition.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBoxPosition.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "Math Teacher", "Physical Teacher", "Computer Science Teacher", "Biology Teacher", "English Teacher" }));

        jLabelBirthdate1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelBirthdate1.setText("Major:");

        jTextFieldGraduSchool.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabelFirstName1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelFirstName1.setText("Username:");

        jLabelLastName2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelLastName2.setText("Password:");

        jTextFieldUsername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabelLastName3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelLastName3.setText("Pepassword:");

        jPasswordField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField2FocusLost(evt);
            }
        });

        jCheckBoxValid.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBoxValid.setText("Valid");

        jLabelLastName4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelLastName4.setText("Graduation School:");

        jCheckBoxHasTeaCert.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBoxHasTeaCert.setText("Has Teacher Certificate");

        jLabelLastName5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelLastName5.setText("Degree:");

        jTextFieldDegree.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextFieldMajor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jComboBoxDepartment.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBoxDepartment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A" }));

        jLabelSex2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelSex2.setText("Department:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelLastName1)
                        .addComponent(jLabelFirstName, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabelSex)
                    .addComponent(jLabelLastName)
                    .addComponent(jLabelSex2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldLastName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldMiddleName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxDepartment, javax.swing.GroupLayout.Alignment.LEADING, 0, 182, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFirstName1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelLastName2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelLastName3, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButtonMan)
                        .addGap(28, 28, 28)
                        .addComponent(jRadioButtonfelmale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(jLabelSex1)))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordField2)
                    .addComponent(jPasswordField1)
                    .addComponent(jTextFieldUsername)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBoxPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(43, 43, 43))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jButtonAddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jButtonResetStu, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jButtonStuCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(229, 229, 229))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBoxValid)
                        .addGap(239, 239, 239)
                        .addComponent(jCheckBoxHasTeaCert)
                        .addGap(90, 90, 90))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelBirthdate)
                                .addGap(18, 18, 18)
                                .addComponent(dateChooserCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(312, 312, 312)
                                .addComponent(jLabelPhone)))
                        .addGap(35, 35, 35)
                        .addComponent(jTextFieldPhone))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelLastName5)
                            .addComponent(jLabelLastName4)
                            .addComponent(jLabelBirthdate1))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldGraduSchool)
                            .addComponent(jTextFieldDegree)
                            .addComponent(jTextFieldMajor, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(142, 142, 142)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelFirstName)
                                    .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelLastName1)
                                        .addComponent(jTextFieldMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelLastName2)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelFirstName1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPasswordField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelLastName)
                                    .addComponent(jLabelLastName3)))
                            .addComponent(jTextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSex)
                            .addComponent(jRadioButtonMan)
                            .addComponent(jRadioButtonfelmale))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSex2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSex1))
                        .addGap(46, 46, 46)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxValid)
                    .addComponent(jCheckBoxHasTeaCert))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBirthdate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateChooserCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelPhone)))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLastName4)
                    .addComponent(jTextFieldGraduSchool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLastName5)
                    .addComponent(jTextFieldDegree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBirthdate1)
                    .addComponent(jTextFieldMajor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonResetStu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonStuCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonResetStuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetStuActionPerformed
        clear();
    }//GEN-LAST:event_jButtonResetStuActionPerformed
    
    private void clear(){
        jTextFieldFirstName.setText("");
        jTextFieldMiddleName.setText("");
        jTextFieldLastName.setText("");
        jRadioButtonMan.setSelected(true);
        jRadioButtonfelmale.setSelected(false);
        Calendar cal1 = Calendar.getInstance();
        cal1.setTime(new Date());
        dateChooserCombo.setSelectedDate(cal1);
        jTextFieldPhone.setText("");
        jTextFieldGraduSchool.setText("");
        jComboBoxPosition.setSelectedIndex(0);
        jTextFieldUsername.setText("");
        jPasswordField1.setText("");
        jPasswordField2.setText("");
        jCheckBoxValid.setSelected(false);
        jCheckBoxHasTeaCert.setSelected(false);
        jTextFieldDegree.setText("");
        jTextFieldMajor.setText("");
        jComboBoxDepartment.setSelectedIndex(0);
    }
    
    private void jButtonStuCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStuCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonStuCancelActionPerformed

    private void jTextFieldPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPhoneKeyTyped
        //allow only numbers
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldPhoneKeyTyped
    
    private boolean verify(){
        if(jTextFieldFirstName.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter First Name");
            jTextFieldFirstName.requestFocus();
            return false;
        }
        if(jTextFieldLastName.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter Last Name");
            jTextFieldLastName.requestFocus();
            return false;
        }
        if(dateChooserCombo.getSelectedDate()==null){
            JOptionPane.showMessageDialog(null, "Please enter select a date");
            dateChooserCombo.requestFocus();
            return false;
        }
        
        if(jTextFieldUsername.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter a Username");
            jTextFieldUsername.requestFocus();
            return false;
        }
        
        char []Password = jPasswordField1.getPassword();
        char []Password2 = jPasswordField2.getPassword();       
        for(int i = 0; i<Password2.length; i++){
            if(Password[i] != Password2[i]){
                JOptionPane.showMessageDialog(null, "Please enter the same Password");
                jPasswordField1.requestFocus();
                return false;
            }
        }
        
        if(dateChooserCombo.getSelectedDate().getTime().compareTo(new Date())>0){
            JOptionPane.showMessageDialog(null, "No Student from future are allowed");
            dateChooserCombo.requestFocus();
            return false;
        }

        return true;
    }
    
    private void jButtonAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddStudentActionPerformed
        String userName = jTextFieldUsername.getText();
        char []Password = jPasswordField1.getPassword();
        char []Password2 = jPasswordField2.getPassword();
        for(int i = 0; i<Password2.length; i++){
            if(Password[i] != Password2[i]){
                JOptionPane.showMessageDialog(null, "Please enter the same Password");
                jPasswordField1.requestFocus();
                return;
            }
        }
        String fN = jTextFieldFirstName.getText();
        String mN = jTextFieldMiddleName.getText();
        String lN = jTextFieldLastName.getText();
        char sex = 'm';
        if(jRadioButtonfelmale.isSelected()){
            sex = 'f';
        }
        boolean valid = jCheckBoxValid.isSelected();
        boolean hasCert = jCheckBoxHasTeaCert.isSelected();
        String Position = jComboBoxPosition.getSelectedItem().toString();
        String department = jComboBoxDepartment.getSelectedItem().toString();
        Calendar bd = dateChooserCombo.getSelectedDate();
        String school = jTextFieldGraduSchool.getText();
        String pNum = jTextFieldPhone.getText();
        String degree = jTextFieldDegree.getText();
        String major = jTextFieldMajor.getText();
        //String firstName, String middleName, String lastName, char sex, int grade, Calendar birthday, int year, String phoneNum, String add

        if(!verify()){
            return;
        }
        Teacher tea = new Teacher(fN, mN, lN, userName, Password, sex, Position,
            valid, hasCert, bd, pNum, school, degree, major, department);
        if(Teacher.operateData('i', tea)){
//            if(ManageTeacherForm.tableExist()){
//                ManageTeacherForm.resetTable();
//            }
            clear();
        }
    }//GEN-LAST:event_jButtonAddStudentActionPerformed

    private void jPasswordField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField2FocusLost
        char []Password = jPasswordField1.getPassword();
        char []Password2 = jPasswordField2.getPassword();       
        for(int i = 0; i<Password2.length; i++){
            if(Password[i] != Password2[i]){
                JOptionPane.showMessageDialog(null, "The Passwords are not same");
                jPasswordField1.requestFocus();
            }
        }
    }//GEN-LAST:event_jPasswordField2FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTeacherForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTeacherForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTeacherForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTeacherForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddTeacherForm st = new AddTeacherForm();
                st.middleScreen();
                //st.dispose();
                //st.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                //st.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                st.setVisible(true);
            }
        });
    }
    
    private void middleScreen(){
        double width = Toolkit.getDefaultToolkit().getScreenSize().getWidth();
        double height = Toolkit.getDefaultToolkit().getScreenSize().getHeight();
        this.setLocation( (int) (width - this.getWidth()) / 2,(int) (height - this.getHeight()) / 2);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserCombo;
    private javax.swing.JButton jButtonAddStudent;
    private javax.swing.JButton jButtonResetStu;
    private javax.swing.JButton jButtonStuCancel;
    private javax.swing.JCheckBox jCheckBoxHasTeaCert;
    private javax.swing.JCheckBox jCheckBoxValid;
    private javax.swing.JComboBox jComboBoxDepartment;
    private javax.swing.JComboBox jComboBoxPosition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBirthdate;
    private javax.swing.JLabel jLabelBirthdate1;
    private javax.swing.JLabel jLabelFirstName;
    private javax.swing.JLabel jLabelFirstName1;
    private javax.swing.JLabel jLabelLastName;
    private javax.swing.JLabel jLabelLastName1;
    private javax.swing.JLabel jLabelLastName2;
    private javax.swing.JLabel jLabelLastName3;
    private javax.swing.JLabel jLabelLastName4;
    private javax.swing.JLabel jLabelLastName5;
    private javax.swing.JLabel jLabelPhone;
    private javax.swing.JLabel jLabelSex;
    private javax.swing.JLabel jLabelSex1;
    private javax.swing.JLabel jLabelSex2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JRadioButton jRadioButtonMan;
    private javax.swing.JRadioButton jRadioButtonfelmale;
    private javax.swing.JTextField jTextFieldDegree;
    private javax.swing.JTextField jTextFieldFirstName;
    private javax.swing.JTextField jTextFieldGraduSchool;
    private javax.swing.JTextField jTextFieldLastName;
    private javax.swing.JTextField jTextFieldMajor;
    private javax.swing.JTextField jTextFieldMiddleName;
    private javax.swing.JTextField jTextFieldPhone;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables

    private void setDepartmentList() {
        String[] departmentList = teacherData.getDepartmentList();
        for(int i = 0; i<departmentList.length; i++){
            jComboBoxDepartment.addItem(departmentList[i]);
        }   
    }
}
