/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jnflsicUI;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jnflsicDataProcess.StuTable;
import jnflsicDataProcess.Student;
import jnflsicTeacherDataProcess.TeaTable;
import jnflsicTeacherDataProcess.Teacher;
import jnflsicTeacherDatabase.teacherData;

/**
 *
 * @author shen
 */
public class ManageTeacherForm extends javax.swing.JFrame {
    //StuTable fillT = new StuTable();
    public ManageTeacherForm() {
        initComponents();
        setDepartmentList();
        ButtonGroup bg = new ButtonGroup();
        bg.add(jRadioButtonMan);
        bg.add(jRadioButtonfelmale);
        jRadioButtonMan.setSelected(true);
        int numCol = jTable1.getColumnCount();
        ////    (dtm2, key, pos, degree, depart, v, has, jTable1.getColumnCount(), tableNumOfRecords, tablePages);
        TeaTable.fillTeaJtable((DefaultTableModel)jTable1.getModel(), "", "", "", "", false, false, numCol, tableNumOfRecords, tablePages);
        //fillT.fillStuJTable(jTable1,valueToSearch, year);
        jLabelTotalNumPag.setText("/"+TeaTable.totalPages());
        model = (DefaultTableModel)jTable1.getModel();
        jTable1.setRowHeight(40);
        jTable1.setShowGrid(true);
        jTable1.setGridColor(Color.GRAY);
        jTable1.setSelectionBackground(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelFirstName = new javax.swing.JLabel();
        jLabelLastName = new javax.swing.JLabel();
        jLabelLastName1 = new javax.swing.JLabel();
        jLabelSex = new javax.swing.JLabel();
        jLabelBirthdate = new javax.swing.JLabel();
        jLabelPhone = new javax.swing.JLabel();
        jLabelAddress = new javax.swing.JLabel();
        jTextFieldFirstName = new javax.swing.JTextField();
        jTextFieldMiddleName = new javax.swing.JTextField();
        jTextFieldLastName = new javax.swing.JTextField();
        jRadioButtonMan = new javax.swing.JRadioButton();
        jRadioButtonfelmale = new javax.swing.JRadioButton();
        dateChooserCombo = new datechooser.beans.DateChooserCombo();
        jTextFieldPhone = new javax.swing.JTextField();
        jButtonManageTeacher = new javax.swing.JButton();
        jButtonTeaAdd = new javax.swing.JButton();
        jLabelSex1 = new javax.swing.JLabel();
        jComboBoxPos = new javax.swing.JComboBox();
        jLabelStuID = new javax.swing.JLabel();
        jTextFieldTeaID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonTeaRemove = new javax.swing.JButton();
        jTextFieldKeyword = new javax.swing.JTextField();
        javax.swing.JLabel jLabelTeaID = new javax.swing.JLabel();
        jLabelStuID2 = new javax.swing.JLabel();
        jLabelStuID3 = new javax.swing.JLabel();
        jButtonTeaSearch = new javax.swing.JButton();
        jButtonManageFrist = new javax.swing.JButton();
        jButtonManagePre = new javax.swing.JButton();
        jTextFieldPage = new javax.swing.JTextField();
        jLabelTotalNumPag = new javax.swing.JLabel();
        jLabelTotalNumPag1 = new javax.swing.JLabel();
        jTextFieldRecord = new javax.swing.JTextField();
        jLabelmRe = new javax.swing.JLabel();
        jButtonManageNext = new javax.swing.JButton();
        jButtonManageLast = new javax.swing.JButton();
        jCheckBoxValid = new javax.swing.JCheckBox();
        jCheckBoxHas = new javax.swing.JCheckBox();
        jComboBoxDepartment = new javax.swing.JComboBox();
        jLabelAddress1 = new javax.swing.JLabel();
        jLabelAddress2 = new javax.swing.JLabel();
        jLabelAddress3 = new javax.swing.JLabel();
        jTextFieldMajor = new javax.swing.JTextField();
        jTextFieldGradu = new javax.swing.JTextField();
        jTextFieldDegree = new javax.swing.JTextField();
        jLabelAddress4 = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jLabelAddress5 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabelAddress6 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jComboBoxPosSearch = new javax.swing.JComboBox();
        jComboBoxDepartmentSearch = new javax.swing.JComboBox();
        jLabelAddress7 = new javax.swing.JLabel();
        jLabelAddress8 = new javax.swing.JLabel();
        jTextFieldDegreeSearch = new javax.swing.JTextField();
        jCheckBoxHasSearch = new javax.swing.JCheckBox();
        jCheckBoxValidSearch = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Manage Teacher");

        jLabelFirstName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelFirstName.setText("First Name:");

        jLabelLastName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelLastName.setText("Last Name:");

        jLabelLastName1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelLastName1.setText("Middle Name:");

        jLabelSex.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelSex.setText("Sex:");

        jLabelBirthdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelBirthdate.setText("BirthDate:");

        jLabelPhone.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPhone.setText("Phone:");

        jLabelAddress.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelAddress.setText("Department:");

        jTextFieldFirstName.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N

        jTextFieldMiddleName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextFieldLastName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jRadioButtonMan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButtonMan.setSelected(true);
        jRadioButtonMan.setText("Male");

        jRadioButtonfelmale.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButtonfelmale.setText("Female");

        dateChooserCombo.setCalendarPreferredSize(new java.awt.Dimension(400, 350));
        dateChooserCombo.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.BOLD, 12));
        dateChooserCombo.setNavigateFont(new java.awt.Font("Shonar Bangla", java.awt.Font.PLAIN, 9));

        jTextFieldPhone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPhoneKeyTyped(evt);
            }
        });

        jButtonManageTeacher.setText("Update");
        jButtonManageTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageTeacherActionPerformed(evt);
            }
        });

        jButtonTeaAdd.setText("Add");
        jButtonTeaAdd.setToolTipText("");
        jButtonTeaAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTeaAddActionPerformed(evt);
            }
        });

        jLabelSex1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelSex1.setText("Position:");

        jComboBoxPos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBoxPos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "Math Teacher", "Physical Teacher", "Computer Science Teacher", "Biology Teacher", "English Teacher" }));

        jLabelStuID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelStuID.setText("Search");

        jTextFieldTeaID.setEditable(false);
        jTextFieldTeaID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TeacherID", "FirstName", "MiddleName", "LastName", "Sex", "Position", "BirthDate", "Department", "Phone", "Valid", "Has Certificate", "Graduation School", "Degree", "Major", "Username", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButtonTeaRemove.setText("Remove");
        jButtonTeaRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTeaRemoveActionPerformed(evt);
            }
        });

        jTextFieldKeyword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabelTeaID.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTeaID.setText("TeacherID:");

        jLabelStuID2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelStuID2.setText("Keyword:");

        jLabelStuID3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelStuID3.setText("Position: ");

        jButtonTeaSearch.setText("Search");
        jButtonTeaSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTeaSearchActionPerformed(evt);
            }
        });

        jButtonManageFrist.setText("First");
        jButtonManageFrist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageFristActionPerformed(evt);
            }
        });

        jButtonManagePre.setText("Previous");
        jButtonManagePre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManagePreActionPerformed(evt);
            }
        });

        jTextFieldPage.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextFieldPage.setText("1");

        jLabelTotalNumPag.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTotalNumPag.setText("/num");

        jLabelTotalNumPag1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTotalNumPag1.setText("Pages");

        jTextFieldRecord.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextFieldRecord.setText("10");

        jLabelmRe.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelmRe.setText("Records/per page");

        jButtonManageNext.setText("Next");
        jButtonManageNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageNextActionPerformed(evt);
            }
        });

        jButtonManageLast.setText("Last");
        jButtonManageLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageLastActionPerformed(evt);
            }
        });

        jCheckBoxValid.setText("Valid");

        jCheckBoxHas.setText("Has Teacher Certificate");

        jComboBoxDepartment.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBoxDepartment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A" }));

        jLabelAddress1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelAddress1.setText("Graduation School:");

        jLabelAddress2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelAddress2.setText("Degree:");

        jLabelAddress3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelAddress3.setText("Major:");

        jTextFieldMajor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextFieldGradu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextFieldDegree.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabelAddress4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelAddress4.setText("Username:");

        jTextFieldUsername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabelAddress5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelAddress5.setText("Password:");

        jLabelAddress6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelAddress6.setText("Repassword:");

        jComboBoxPosSearch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBoxPosSearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "Math Teacher", "Physical Teacher", "Computer Science Teacher", "Biology Teacher", "English Teacher" }));

        jComboBoxDepartmentSearch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBoxDepartmentSearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A" }));

        jLabelAddress7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelAddress7.setText("Department:");

        jLabelAddress8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelAddress8.setText("Degree:");

        jTextFieldDegreeSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jCheckBoxHasSearch.setText("Has Teacher Certificate");

        jCheckBoxValidSearch.setText("Valid");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabelFirstName))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jLabelTeaID))
                                    .addComponent(jLabelLastName1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelLastName, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                                    .addComponent(jTextFieldMiddleName, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldFirstName)
                                    .addComponent(jTextFieldTeaID)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabelSex)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonMan, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jRadioButtonfelmale)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelAddress3)
                            .addComponent(jLabelSex1)
                            .addComponent(jLabelBirthdate)
                            .addComponent(jLabelPhone)
                            .addComponent(jLabelAddress)
                            .addComponent(jLabelAddress1)
                            .addComponent(jLabelAddress2)
                            .addComponent(jLabelAddress4)
                            .addComponent(jLabelAddress5)
                            .addComponent(jLabelAddress6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPhone)
                            .addComponent(dateChooserCombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldMajor, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldGradu, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldDegree, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jComboBoxPos, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jCheckBoxValid)
                                                    .addComponent(jCheckBoxHas)))
                                            .addComponent(jComboBoxDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jButtonTeaAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)
                                        .addComponent(jButtonManageTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonTeaRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25))
                                    .addComponent(jTextFieldUsername, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPasswordField2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(14, 14, 14)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonManageFrist, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jButtonManagePre, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jTextFieldPage, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelTotalNumPag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTotalNumPag1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelmRe)
                        .addGap(50, 50, 50)
                        .addComponent(jButtonManageNext, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonManageLast, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelStuID)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabelAddress8)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextFieldDegreeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabelAddress7))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabelStuID2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextFieldKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30)
                                                .addComponent(jLabelStuID3)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBoxPosSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBoxDepartmentSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(51, 51, 51)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBoxHasSearch)
                                            .addComponent(jCheckBoxValidSearch))))
                                .addGap(52, 52, 52)
                                .addComponent(jButtonTeaSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(77, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTeaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTeaID))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFirstName)
                            .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLastName1)
                            .addComponent(jTextFieldMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxDepartmentSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAddress7)
                            .addComponent(jLabelAddress8)
                            .addComponent(jTextFieldDegreeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonTeaSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxHasSearch)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelStuID)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelStuID3)
                                .addComponent(jComboBoxPosSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBoxValidSearch))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelStuID2)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelLastName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSex)
                            .addComponent(jRadioButtonMan)
                            .addComponent(jRadioButtonfelmale)
                            .addComponent(jCheckBoxValid))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSex1)
                            .addComponent(jComboBoxPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxHas))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dateChooserCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelBirthdate))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelPhone)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelAddress)
                                    .addComponent(jComboBoxDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelAddress1)
                                    .addComponent(jTextFieldGradu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAddress2)
                            .addComponent(jTextFieldDegree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAddress3)
                            .addComponent(jTextFieldMajor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAddress4)
                            .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonTeaAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonManageTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonTeaRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelAddress5)
                                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelAddress6)
                                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 36, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonManageNext, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonManageLast, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelTotalNumPag)
                                .addComponent(jLabelTotalNumPag1)
                                .addComponent(jTextFieldRecord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelmRe))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonManageFrist, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonManagePre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private static void clear(){
        jTextFieldTeaID.setText("");
        jTextFieldFirstName.setText("");
        jTextFieldMiddleName.setText("");
        jTextFieldLastName.setText("");
        jRadioButtonMan.setSelected(true);
        jRadioButtonfelmale.setSelected(false);
        Calendar cal1 = Calendar.getInstance();
        cal1.setTime(new Date());
        dateChooserCombo.setSelectedDate(cal1);
        jCheckBoxValid.setSelected(false);
        jCheckBoxHas.setSelected(false);
        jTextFieldPhone.setText("");
        jComboBoxDepartment.setSelectedIndex(0);
        jTextFieldGradu.setText("");
        jComboBoxPos.setSelectedIndex(0);
        jTextFieldDegree.setText("");
        jTextFieldMajor.setText("");
        jTextFieldUsername.setText("");
        jPasswordField1.setText("");
        jPasswordField2.setText("");
    }
    
    private void jButtonTeaAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTeaAddActionPerformed
        AddTeacherForm atf = new AddTeacherForm();
        atf.setVisible(true);
        atf.pack();
        atf.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonTeaAddActionPerformed

    private void jTextFieldPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPhoneKeyTyped
        //allow only numbers
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldPhoneKeyTyped
    
    private boolean verify(){
        if(jTextFieldFirstName.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter First Name");
            jTextFieldFirstName.requestFocus();
            return false;
        }
        if(jTextFieldLastName.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter Last Name");
            jTextFieldLastName.requestFocus();
            return false;
        }
        if(dateChooserCombo.getSelectedDate()==null){
            JOptionPane.showMessageDialog(null, "Please enter select a date");
            dateChooserCombo.requestFocus();
            return false;
        }
//        if(jTextFieldYear.getText().equals("")||jTextFieldYear.getText().length()!=4){
//            JOptionPane.showMessageDialog(null, "Please enter enroll year");
//            jTextFieldYear.requestFocus();
//            return false;
//        }
        
//        Date now = new Date();
//        Calendar n = Calendar.getInstance();
//        n.setTime(now);
//        int nY = n.get(Calendar.YEAR);
//        if(nY-Integer.parseInt(jTextFieldYear.getText())<0){
//            JOptionPane.showMessageDialog(null, "Please enter corrected enroll year");
//            jTextFieldYear.requestFocus();
//            return false;
//        }
        
        
        if(dateChooserCombo.getSelectedDate().getTime().compareTo(new Date())>0){
            JOptionPane.showMessageDialog(null, "No Student from future are allowed");
            dateChooserCombo.requestFocus();
            return false;
        }
        if(jTextFieldUsername.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter a username");
            jTextFieldUsername.requestFocus();
            return false;
        }
        if(!String.valueOf(jPasswordField1.getPassword()).equals(String.valueOf(jPasswordField2.getPassword()))){
            JOptionPane.showMessageDialog(null, "Two password are not same");
            jPasswordField1.requestFocus();
            return false;
        }
        return true;
    }
    
    private void jButtonManageTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageTeacherActionPerformed
        String fN = jTextFieldFirstName.getText();
        String mN = jTextFieldMiddleName.getText();
        String lN = jTextFieldLastName.getText();
        char sex = 'm';
        if(jRadioButtonfelmale.isSelected()){
            sex = 'f';
        }
        String pos = jComboBoxPos.getSelectedItem().toString();
        boolean valid = jCheckBoxValid.isSelected();
        boolean has = jCheckBoxHas.isSelected();
        
        Calendar bd = dateChooserCombo.getSelectedDate();

        String pNum = jTextFieldPhone.getText();
        String department = jComboBoxDepartment.getSelectedItem().toString();
        String gSchool = jTextFieldGradu.getText();
        String degree = jTextFieldDegree.getText();
        String major = jTextFieldMajor.getText();
        String user = jTextFieldUsername.getText();
        char [] pass1 = jPasswordField1.getPassword();
        if(pass1.length>20){
            pass1 = null;
        }
        
        if(!verify()){
            return;
        }

        Teacher tea = new Teacher(fN,mN,lN,user,pass1,sex,pos,valid,has, bd, pNum, gSchool,degree, major, department);
        tea.setTeaID(Integer.parseInt(jTextFieldTeaID.getText()));
        if(Teacher.operateData('u', tea)){
            resetTable();
            clear();
        }
    }//GEN-LAST:event_jButtonManageTeacherActionPerformed

    private void jButtonTeaRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTeaRemoveActionPerformed
        if(jTextFieldTeaID.getText().equals("")){
            return;
        }
        int id = Integer.parseInt(jTextFieldTeaID.getText());
        Teacher tea = new Teacher();
        tea.setTeaID(id);
        if(Teacher.operateData('d', tea)){
            resetTable();
            clear();
        }
    }//GEN-LAST:event_jButtonTeaRemoveActionPerformed
    
    public static boolean tableExist(){
        return jTable1 != null;
    }
    
    public static void resetTable(){
        //System.out.println("aha");
        //jTable1 = new javax.swing.JTable();
        clear();
        //jTable1.clearSelection();
        tablePages = Integer.parseInt(jTextFieldPage.getText());
        tableNumOfRecords = Integer.parseInt(jTextFieldRecord.getText());
        //jTable1.setModel(null);
        //System.out.println("BEreset"+jTable1);
        //model = (DefaultTableModel)jTable1.getModel();
        DefaultTableModel dtm2 = (DefaultTableModel)jTable1.getModel();
        dtm2.setDataVector(null, new String [] {
                "TeacherID", "FirstName", "MiddleName", "LastName", "Sex", "Position", "BirthDate", "Department", "Phone", "Valid", "Has Certificate", "Graduation School", "Degree", "Major", "Username", "Password"
            });
//        jTable1.setModel(new DefaultTableModel(null,
//            new String [] {
//                "StudentID", "FirstName", "MiddleName", "LastName", "Sex", "Grade", "BirthDate", "Enrolled Year", "Phone", "Address"
//            }));
        String key = jTextFieldKeyword.getText();
        String pos = jComboBoxPosSearch.getSelectedItem().toString();
        if(pos.equals("N/A")){
            pos = "";
        }
        String degree = jTextFieldDegreeSearch.getText();
        String depart = jComboBoxDepartmentSearch.getSelectedItem().toString();
        if(depart.equals("N/A")){
            depart = "";
        }
        boolean v = jCheckBoxValidSearch.isSelected();
        boolean has = jCheckBoxHasSearch.isSelected();
        System.out.println("has:"+has);
        //System.out.println("reset"+jTable1);
        TeaTable.fillTeaJtable(dtm2, key, pos, degree, depart, v, has, jTable1.getColumnCount(), tableNumOfRecords, tablePages);
        jLabelTotalNumPag.setText("/"+TeaTable.totalPages());
    }
    
    private static boolean isNumeric(String str) {  
      for (int i = str.length(); --i >= 0;) {     
       if (!Character.isDigit(str.charAt(i))) {  
        return false;  
       }  
      }  
       return true;  
    } 
    
    private void jButtonTeaSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTeaSearchActionPerformed
        jTextFieldPage.setText("1");
        resetTable();
    }//GEN-LAST:event_jButtonTeaSearchActionPerformed

    private void jButtonManageFristActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageFristActionPerformed
        //tablePages = 1;
        jTextFieldPage.setText("1");
        tableNumOfRecords = Integer.parseInt(jTextFieldRecord.getText());
        resetTable();
    }//GEN-LAST:event_jButtonManageFristActionPerformed

    private void jButtonManagePreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManagePreActionPerformed
        int n = Integer.parseInt(jTextFieldPage.getText())-1;
        if(n==0){
            n = 1;
        }
        jTextFieldPage.setText(n+"");
        tableNumOfRecords = Integer.parseInt(jTextFieldRecord.getText());
        //jTextFieldPage.setText(tablePages+"");
        resetTable();
    }//GEN-LAST:event_jButtonManagePreActionPerformed

    private void jButtonManageNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageNextActionPerformed
        int n = Integer.parseInt(jTextFieldPage.getText())+1;
        if(n>Integer.parseInt(jLabelTotalNumPag.getText().substring(1, 2))){
            n = Integer.parseInt(jLabelTotalNumPag.getText().substring(1, 2));
        }
        jTextFieldPage.setText(n+"");
        tableNumOfRecords = Integer.parseInt(jTextFieldRecord.getText());
        //jTextFieldPage.setText(tablePages+"");
        resetTable();
    }//GEN-LAST:event_jButtonManageNextActionPerformed

    private void jButtonManageLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageLastActionPerformed
        //tablePages = Integer.parseInt(jLabelTotalNumPag.getText().substring(1,2));
                //tablePages = 1;
        jTextFieldPage.setText(jLabelTotalNumPag.getText().substring(1,2));
        tableNumOfRecords = Integer.parseInt(jTextFieldRecord.getText());
        //jTextFieldPage.setText(tablePages+"");
        resetTable();
    }//GEN-LAST:event_jButtonManageLastActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        rowIndex = jTable1.getSelectedRow();
        //System.out.println("select"+jTable1);
       // model = (DefaultTableModel)jTable1.getModel();
        jTextFieldTeaID.setText(model.getValueAt(rowIndex, 0).toString());
        //System.out.println(model.getValueAt(rowIndex, 0).toString());
//        System.out.println(model.getValueAt(rowIndex, 0).toString());
        //System.out.println("model "+model.toString());
        jTextFieldFirstName.setText(model.getValueAt(rowIndex, 1).toString());
        jTextFieldMiddleName.setText(model.getValueAt(rowIndex, 2).toString());
        jTextFieldLastName.setText(model.getValueAt(rowIndex, 3).toString());
        if(model.getValueAt(rowIndex, 4).toString().equals("m")){
            jRadioButtonMan.setSelected(true);
        }else{
            jRadioButtonfelmale.setSelected(false);
        }
        
        String g = model.getValueAt(rowIndex, 5).toString();
        jComboBoxPos.setSelectedItem(g);
        //System.out.println(model.getValueAt(rowIndex, 6));
        String d = model.getValueAt(rowIndex, 6).toString();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        try {
            Date date = sdf.parse(d);
            Calendar calendar = Calendar.getInstance();
            calendar.setTime(date);
            dateChooserCombo.setSelectedDate(calendar);
        } catch (ParseException ex) {
            Logger.getLogger(ManageTeacherForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        Object o = model.getValueAt(rowIndex, 7);
        //String dep = .toString();
        if(o == null){
            o = "N/A";
        }
        jComboBoxDepartment.setSelectedItem(o.toString());
        jTextFieldPhone.setText(model.getValueAt(rowIndex, 8).toString());
        jCheckBoxValid.setSelected(false);
        if(model.getValueAt(rowIndex, 9).toString().equals("Working")){
            jCheckBoxValid.setSelected(true);
        }
        jCheckBoxHas.setSelected(false);
        if(model.getValueAt(rowIndex, 10).toString().equals("Has Certificate")){
            jCheckBoxValid.setSelected(true);
        }
        
        jTextFieldGradu.setText(model.getValueAt(rowIndex, 11).toString());
        jTextFieldDegree.setText(model.getValueAt(rowIndex, 12).toString());
        jTextFieldMajor.setText(model.getValueAt(rowIndex, 13).toString());
        jTextFieldUsername.setText(model.getValueAt(rowIndex, 14).toString());
        jPasswordField1.setText(model.getValueAt(rowIndex, 15).toString());
        jPasswordField2.setText(model.getValueAt(rowIndex, 15).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_UP || evt.getKeyCode()==KeyEvent.VK_DOWN){
            rowIndex = jTable1.getSelectedRow();
            //System.out.println("select"+jTable1);
           // model = (DefaultTableModel)jTable1.getModel();
            jTextFieldTeaID.setText(model.getValueAt(rowIndex, 0).toString());
            //System.out.println(model.getValueAt(rowIndex, 0).toString());
    //        System.out.println(model.getValueAt(rowIndex, 0).toString());
            //System.out.println("model "+model.toString());
            jTextFieldFirstName.setText(model.getValueAt(rowIndex, 1).toString());
            jTextFieldMiddleName.setText(model.getValueAt(rowIndex, 2).toString());
            jTextFieldLastName.setText(model.getValueAt(rowIndex, 3).toString());
            if(model.getValueAt(rowIndex, 4).toString().equals("m")){
                jRadioButtonMan.setSelected(true);
            }else{
                jRadioButtonfelmale.setSelected(false);
            }

            String g = model.getValueAt(rowIndex, 5).toString();
            jComboBoxPos.setSelectedItem(g);
            //System.out.println(model.getValueAt(rowIndex, 6));
            String d = model.getValueAt(rowIndex, 6).toString();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            try {
                Date date = sdf.parse(d);
                Calendar calendar = Calendar.getInstance();
                calendar.setTime(date);
                dateChooserCombo.setSelectedDate(calendar);
            } catch (ParseException ex) {
                Logger.getLogger(ManageTeacherForm.class.getName()).log(Level.SEVERE, null, ex);
            }

            jComboBoxDepartment.setSelectedItem(model.getValueAt(rowIndex, 7).toString());
            jTextFieldPhone.setText(model.getValueAt(rowIndex, 8).toString());
            jCheckBoxValid.setSelected(false);
            if(model.getValueAt(rowIndex, 9).toString().equals("Working")){
                jCheckBoxValid.setSelected(true);
            }
            jCheckBoxHas.setSelected(false);
            if(model.getValueAt(rowIndex, 10).toString().equals("Has Certificate")){
                jCheckBoxValid.setSelected(true);
            }

            jTextFieldGradu.setText(model.getValueAt(rowIndex, 11).toString());
            jTextFieldDegree.setText(model.getValueAt(rowIndex, 12).toString());
            jTextFieldMajor.setText(model.getValueAt(rowIndex, 13).toString());
            jTextFieldUsername.setText(model.getValueAt(rowIndex, 14).toString());
            jPasswordField1.setText(model.getValueAt(rowIndex, 15).toString());
            jPasswordField2.setText(model.getValueAt(rowIndex, 15).toString());
        }
    }//GEN-LAST:event_jTable1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageTeacherForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageTeacherForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageTeacherForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageTeacherForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ManageTeacherForm st = new ManageTeacherForm();
                st.middleScreen();
                st.setVisible(true);
            }
        });
    }
    
    private void middleScreen(){
        double width = Toolkit.getDefaultToolkit().getScreenSize().getWidth();
        double height = Toolkit.getDefaultToolkit().getScreenSize().getHeight();
        this.setLocation( (int) (width - this.getWidth()) / 2,(int) (height - this.getHeight()) / 2);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static datechooser.beans.DateChooserCombo dateChooserCombo;
    private javax.swing.JButton jButtonManageFrist;
    private javax.swing.JButton jButtonManageLast;
    private javax.swing.JButton jButtonManageNext;
    private javax.swing.JButton jButtonManagePre;
    private javax.swing.JButton jButtonManageTeacher;
    private javax.swing.JButton jButtonTeaAdd;
    private javax.swing.JButton jButtonTeaRemove;
    private javax.swing.JButton jButtonTeaSearch;
    private static javax.swing.JCheckBox jCheckBoxHas;
    private static javax.swing.JCheckBox jCheckBoxHasSearch;
    private static javax.swing.JCheckBox jCheckBoxValid;
    private static javax.swing.JCheckBox jCheckBoxValidSearch;
    private static javax.swing.JComboBox jComboBoxDepartment;
    private static javax.swing.JComboBox jComboBoxDepartmentSearch;
    private static javax.swing.JComboBox jComboBoxPos;
    private static javax.swing.JComboBox jComboBoxPosSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelAddress1;
    private javax.swing.JLabel jLabelAddress2;
    private javax.swing.JLabel jLabelAddress3;
    private javax.swing.JLabel jLabelAddress4;
    private javax.swing.JLabel jLabelAddress5;
    private javax.swing.JLabel jLabelAddress6;
    private javax.swing.JLabel jLabelAddress7;
    private javax.swing.JLabel jLabelAddress8;
    private javax.swing.JLabel jLabelBirthdate;
    private javax.swing.JLabel jLabelFirstName;
    private javax.swing.JLabel jLabelLastName;
    private javax.swing.JLabel jLabelLastName1;
    private javax.swing.JLabel jLabelPhone;
    private javax.swing.JLabel jLabelSex;
    private javax.swing.JLabel jLabelSex1;
    private javax.swing.JLabel jLabelStuID;
    private javax.swing.JLabel jLabelStuID2;
    private javax.swing.JLabel jLabelStuID3;
    private static javax.swing.JLabel jLabelTotalNumPag;
    private javax.swing.JLabel jLabelTotalNumPag1;
    private javax.swing.JLabel jLabelmRe;
    private static javax.swing.JPanel jPanel1;
    private static javax.swing.JPasswordField jPasswordField1;
    private static javax.swing.JPasswordField jPasswordField2;
    private static javax.swing.JRadioButton jRadioButtonMan;
    private static javax.swing.JRadioButton jRadioButtonfelmale;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    private static javax.swing.JTextField jTextFieldDegree;
    private static javax.swing.JTextField jTextFieldDegreeSearch;
    private static javax.swing.JTextField jTextFieldFirstName;
    private static javax.swing.JTextField jTextFieldGradu;
    private static javax.swing.JTextField jTextFieldKeyword;
    private static javax.swing.JTextField jTextFieldLastName;
    private static javax.swing.JTextField jTextFieldMajor;
    private static javax.swing.JTextField jTextFieldMiddleName;
    private static javax.swing.JTextField jTextFieldPage;
    private static javax.swing.JTextField jTextFieldPhone;
    public static javax.swing.JTextField jTextFieldRecord;
    private static javax.swing.JTextField jTextFieldTeaID;
    private static javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
    private static int tablePages = 1;
    private static int tableNumOfRecords = 10;
    private static int rowIndex = 0;
    private static DefaultTableModel model = null;

    private void setDepartmentList() {
        String[] departmentList = teacherData.getDepartmentList();
        for(int i = 0; i<departmentList.length; i++){
            jComboBoxDepartment.addItem(departmentList[i]);
            jComboBoxDepartmentSearch.addItem(departmentList[i]);
        }  
    }
}
