/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jnflsicUI;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jnflsicCourseDataProcess.Course;
import jnflsicCourseDataProcess.CourseTable;
import jnflsicCourseDatabase.CourseData;
import jnflsicDataProcess.StuTable;
import jnflsicDataProcess.Student;
import jnflsicDepDataProcess.DepTable;
import jnflsicDepDataProcess.Department;

/**
 *
 * @author shen
 */
public class ManageCourseForm extends javax.swing.JFrame {
    //StuTable fillT = new StuTable();
    public ManageCourseForm() {
        initComponents();
        setDepartmentList();
        
        int numCol = jTable1.getColumnCount();
        CourseTable.fillCourseJtable((DefaultTableModel)jTable1.getModel(), "", -1, "N/A", numCol, tableNumOfRecords, tablePages);
        //fillT.fillStuJTable(jTable1,valueToSearch, year);
        jLabelTotalNumPag.setText("/"+CourseTable.totalPages());
        model = (DefaultTableModel)jTable1.getModel();
        jTable1.setRowHeight(40);
        jTable1.setShowGrid(true);
        jTable1.setGridColor(Color.GRAY);
        jTable1.setSelectionBackground(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelFirstName = new javax.swing.JLabel();
        jLabelLastName1 = new javax.swing.JLabel();
        jLabelPhone = new javax.swing.JLabel();
        jLabelAddress = new javax.swing.JLabel();
        jTextFieldCourseName = new javax.swing.JTextField();
        jTextFieldPrerequirement = new javax.swing.JTextField();
        jScrollPanelAddress = new javax.swing.JScrollPane();
        jTexCourseDescription = new javax.swing.JTextArea();
        jButtonManageCourse = new javax.swing.JButton();
        jButtonCourseAdd = new javax.swing.JButton();
        jLabelStuID = new javax.swing.JLabel();
        jTextFieldCourseID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonCosRemove = new javax.swing.JButton();
        jTextFieldKeyword = new javax.swing.JTextField();
        jLabelDepID = new javax.swing.JLabel();
        jLabelStuID2 = new javax.swing.JLabel();
        jLabelLeader = new javax.swing.JLabel();
        jButtonDepSearch = new javax.swing.JButton();
        jButtonManageFrist = new javax.swing.JButton();
        jButtonManagePre = new javax.swing.JButton();
        jTextFieldPage = new javax.swing.JTextField();
        jLabelTotalNumPag = new javax.swing.JLabel();
        jLabelTotalNumPag1 = new javax.swing.JLabel();
        jTextFieldRecord = new javax.swing.JTextField();
        jLabelmRe = new javax.swing.JLabel();
        jButtonManageNext = new javax.swing.JButton();
        jButtonManageLast = new javax.swing.JButton();
        jCheckBoxCourseActive = new javax.swing.JCheckBox();
        jLabelLastName2 = new javax.swing.JLabel();
        jComboBoxCredit = new javax.swing.JComboBox();
        jLabelLastName3 = new javax.swing.JLabel();
        jComboBoxArea = new javax.swing.JComboBox();
        jComboBoxDepartment = new javax.swing.JComboBox();
        jLabelPhone1 = new javax.swing.JLabel();
        jLabelLeader1 = new javax.swing.JLabel();
        jComboBoxKeyDepart = new javax.swing.JComboBox();
        jComboBoxKeyArea = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Manage Course");

        jLabelFirstName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelFirstName.setText("Course Name:");

        jLabelLastName1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelLastName1.setText("Course Active:");

        jLabelPhone.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPhone.setText("Course Department:");

        jLabelAddress.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelAddress.setText("Course Description:");

        jTextFieldCourseName.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N

        jTextFieldPrerequirement.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTexCourseDescription.setColumns(20);
        jTexCourseDescription.setRows(5);
        jScrollPanelAddress.setViewportView(jTexCourseDescription);

        jButtonManageCourse.setText("Update");
        jButtonManageCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageCourseActionPerformed(evt);
            }
        });

        jButtonCourseAdd.setText("Add");
        jButtonCourseAdd.setToolTipText("");
        jButtonCourseAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCourseAddActionPerformed(evt);
            }
        });

        jLabelStuID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelStuID.setText("Search");

        jTextFieldCourseID.setEditable(false);
        jTextFieldCourseID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CourseID", "Course Name", "Active", "Credit", "Area", "Department Name", "Prerequirement", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButtonCosRemove.setText("Remove");
        jButtonCosRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCosRemoveActionPerformed(evt);
            }
        });

        jTextFieldKeyword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabelDepID.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelDepID.setText("CourseID:");

        jLabelStuID2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelStuID2.setText("Keyword:");

        jLabelLeader.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelLeader.setText("Course Department: ");

        jButtonDepSearch.setText("Search");
        jButtonDepSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDepSearchActionPerformed(evt);
            }
        });

        jButtonManageFrist.setText("First");
        jButtonManageFrist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageFristActionPerformed(evt);
            }
        });

        jButtonManagePre.setText("Previous");
        jButtonManagePre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManagePreActionPerformed(evt);
            }
        });

        jTextFieldPage.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextFieldPage.setText("1");

        jLabelTotalNumPag.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTotalNumPag.setText("/num");

        jLabelTotalNumPag1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTotalNumPag1.setText("Pages");

        jTextFieldRecord.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextFieldRecord.setText("10");

        jLabelmRe.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelmRe.setText("Records/per page");

        jButtonManageNext.setText("Next");
        jButtonManageNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageNextActionPerformed(evt);
            }
        });

        jButtonManageLast.setText("Last");
        jButtonManageLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageLastActionPerformed(evt);
            }
        });

        jCheckBoxCourseActive.setText("Active");

        jLabelLastName2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelLastName2.setText("Course Credit:");

        jComboBoxCredit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabelLastName3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelLastName3.setText("Course Area:");

        jComboBoxArea.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "Advanced Placement (AP)", "Advanced Level (AL)", "Advanced Subsidiary Level (AS)", "National Course", "Second Language", "Others" }));

        jComboBoxDepartment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A" }));

        jLabelPhone1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPhone1.setText("Course Prerequirement:");

        jLabelLeader1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelLeader1.setText("Course Area: ");

        jComboBoxKeyDepart.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A" }));

        jComboBoxKeyArea.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "Advanced Placement (AP)", "Advanced Level (AL)", "Advanced Subsidiary Level (AS)", "National Course", "Second Language", "Others" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jButtonCourseAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(jButtonManageCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButtonCosRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabelAddress)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPanelAddress))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelLastName2)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelLastName3, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelPhone, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelPhone1, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelLastName1)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelDepID)
                                            .addComponent(jLabelFirstName))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldCourseName, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                                    .addComponent(jTextFieldCourseID)
                                    .addComponent(jCheckBoxCourseActive)
                                    .addComponent(jComboBoxArea, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxDepartment, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextFieldPrerequirement, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap())
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelStuID)
                                    .addGap(230, 230, 230)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelStuID2)
                                .addGap(31, 31, 31)
                                .addComponent(jTextFieldKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabelLeader)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxKeyDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelLeader1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxKeyArea, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonDepSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jButtonManageFrist, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jButtonManagePre, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldPage, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelTotalNumPag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTotalNumPag1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelmRe)
                        .addGap(50, 50, 50)
                        .addComponent(jButtonManageNext, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonManageLast, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabelStuID)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelLeader)
                        .addComponent(jButtonDepSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelLeader1)
                        .addComponent(jComboBoxKeyDepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxKeyArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelStuID2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDepID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFirstName))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLastName1)
                            .addComponent(jCheckBoxCourseActive))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLastName2)
                            .addComponent(jComboBoxCredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLastName3)
                            .addComponent(jComboBoxArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPhone)
                            .addComponent(jComboBoxDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPrerequirement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPhone1))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPanelAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonManageNext, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonManageLast, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelTotalNumPag)
                        .addComponent(jLabelTotalNumPag1)
                        .addComponent(jTextFieldRecord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelmRe))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonManageFrist, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonManagePre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonCourseAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonManageCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonCosRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private static void clear(){
        jTextFieldCourseID.setText("");
        jTextFieldCourseName.setText("");
        jCheckBoxCourseActive.setSelected(false);
        jComboBoxCredit.setSelectedIndex(0);
        jComboBoxArea.setSelectedIndex(0);
        jComboBoxDepartment.setSelectedIndex(0);
        jTextFieldPrerequirement.setText("");
        jTexCourseDescription.setText("");
    }
    
    private void jButtonCourseAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCourseAddActionPerformed
            AddCourseForm ACF = new AddCourseForm();
            ACF.setVisible(true);
            ACF.pack();
            ACF.setLocationRelativeTo(null);
            ACF.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButtonCourseAddActionPerformed
    
    private boolean verify(){
        if(jTextFieldCourseName.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter Department Name");
            jTextFieldCourseName.requestFocus();
            return false;
        }
 
        return true;
    }
    
    private void jButtonManageCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageCourseActionPerformed
        int courseID = Integer.parseInt(jTextFieldCourseID.getText());
        String courseName = jTextFieldCourseName.getText();        
        String Prerequirement = jTextFieldPrerequirement.getText();
        String description = jTexCourseDescription.getText();
        boolean active = jCheckBoxCourseActive.isSelected();
        int credit = Integer.parseInt(jComboBoxCredit.getModel().getSelectedItem().toString());
        String area = jComboBoxArea.getModel().getSelectedItem().toString();      
        String department = jComboBoxDepartment.getModel().getSelectedItem().toString();
        
        int departmentID = -1;

        if(!verify()){
            return;
        }
        //String Name, String pReq, String des, boolean act, String c, String a, String depart
        Course cos = new Course(courseName, Prerequirement, description, active, credit, area, department);
        cos.setCourseID(courseID);
        if(!department.equals("N/A")){
            departmentID = cos.getDepartmentID();
        }
        
        cos.setDepartmentID(departmentID);
        System.out.println("coooooo"+cos.getCourseName());
        if(Course.operateData('u', cos)){
            resetTable();
            clear();
        }
    }//GEN-LAST:event_jButtonManageCourseActionPerformed

    private void jButtonCosRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCosRemoveActionPerformed
        if(jTextFieldCourseID.getText().equals("")){
            return;
        }
        int id = Integer.parseInt(jTextFieldCourseID.getText());
        Course c = new Course();
        c.setCourseID(id);
        //d.setID(id);
        if(Course.operateData('d', c)){
            resetTable();
            clear();
        }
    }//GEN-LAST:event_jButtonCosRemoveActionPerformed
    
    public static boolean tableExist(){
        return jTable1 != null;
    }
    
    public static void resetTable(){
        clear();
        tablePages = Integer.parseInt(jTextFieldPage.getText());
        tableNumOfRecords = Integer.parseInt(jTextFieldRecord.getText());
        DefaultTableModel dtm2 = (DefaultTableModel)jTable1.getModel();
        dtm2.setDataVector(null, new String [] {
                "CourseID", "Course Name", "Active", "Credit", "Area", "Department Name", "Prerequirement", "Description"
            });
        String key = jTextFieldKeyword.getText();
        String department = jComboBoxKeyDepart.getModel().getSelectedItem().toString();
        int departmentID = CourseData.getDepartID(department);
        String courseArea = jComboBoxKeyArea.getModel().getSelectedItem().toString();

        CourseTable.fillCourseJtable(dtm2, key, departmentID, courseArea, jTable1.getColumnCount(), tableNumOfRecords, tablePages);
        jLabelTotalNumPag.setText("/"+CourseTable.totalPages());
    }
    
    private void setDepartmentList(){
        String[] departmentList = CourseData.getDepartmentList();
        for(int i = 0; i<departmentList.length; i++){
            jComboBoxDepartment.addItem(departmentList[i]);
            jComboBoxKeyDepart.addItem(departmentList[i]);
        }
    }
        
    private void jButtonDepSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDepSearchActionPerformed
        jTextFieldPage.setText("1");
        resetTable();
    }//GEN-LAST:event_jButtonDepSearchActionPerformed

    private void jButtonManageFristActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageFristActionPerformed
        //tablePages = 1;
        jTextFieldPage.setText("1");
        tableNumOfRecords = Integer.parseInt(jTextFieldRecord.getText());
        resetTable();
    }//GEN-LAST:event_jButtonManageFristActionPerformed

    private void jButtonManagePreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManagePreActionPerformed
        int n = Integer.parseInt(jTextFieldPage.getText())-1;
        if(n==0){
            n = 1;
        }
        jTextFieldPage.setText(n+"");
        tableNumOfRecords = Integer.parseInt(jTextFieldRecord.getText());
        //jTextFieldPage.setText(tablePages+"");
        resetTable();
    }//GEN-LAST:event_jButtonManagePreActionPerformed

    private void jButtonManageNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageNextActionPerformed
        int n = Integer.parseInt(jTextFieldPage.getText())+1;
        if(n>Integer.parseInt(jLabelTotalNumPag.getText().substring(1, 2))){
            n = Integer.parseInt(jLabelTotalNumPag.getText().substring(1, 2));
        }
        jTextFieldPage.setText(n+"");
        tableNumOfRecords = Integer.parseInt(jTextFieldRecord.getText());
        //jTextFieldPage.setText(tablePages+"");
        resetTable();
    }//GEN-LAST:event_jButtonManageNextActionPerformed

    private void jButtonManageLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageLastActionPerformed
        //tablePages = Integer.parseInt(jLabelTotalNumPag.getText().substring(1,2));
                //tablePages = 1;
        jTextFieldPage.setText(jLabelTotalNumPag.getText().substring(1,2));
        tableNumOfRecords = Integer.parseInt(jTextFieldRecord.getText());
        //jTextFieldPage.setText(tablePages+"");
        resetTable();
    }//GEN-LAST:event_jButtonManageLastActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        rowIndex = jTable1.getSelectedRow();
        jTextFieldCourseID.setText(model.getValueAt(rowIndex, 0).toString());
        jTextFieldCourseName.setText(model.getValueAt(rowIndex, 1).toString());
        jCheckBoxCourseActive.setSelected(false);
        if(model.getValueAt(rowIndex, 2).toString().equals("Open")){
            jCheckBoxCourseActive.setSelected(true);
        }else{
            jCheckBoxCourseActive.setSelected(false);
        }
        int credit = Integer.parseInt(model.getValueAt(rowIndex, 3).toString());
        jComboBoxCredit.getModel().setSelectedItem(credit);
        
        String area = model.getValueAt(rowIndex, 4).toString();
        if(area.equals("")){
            area = "N/A";
        }
        jComboBoxArea.getModel().setSelectedItem(area);
        String department = "N/A";
        if(model.getValueAt(rowIndex, 5)==null){
            department = "N/A";
        }else{
            department = model.getValueAt(rowIndex, 5).toString();
        }
//        String department = model.getValueAt(rowIndex, 5).toString();
//        System.out.println(department);
//        if(department.equals("")){
//            department = "N/A";
//        }
        jComboBoxDepartment.getModel().setSelectedItem(department);
        jTextFieldPrerequirement.setText(model.getValueAt(rowIndex, 6).toString());
        //System.out.println(model.getValueAt(rowIndex, 6).toString());
        String desc = model.getValueAt(rowIndex, 7).toString();
        if(desc==null){
            desc = "";
        }
        jTexCourseDescription.setText(desc);
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_UP || evt.getKeyCode()==KeyEvent.VK_DOWN){
            rowIndex = jTable1.getSelectedRow();
            rowIndex = jTable1.getSelectedRow();
            jTextFieldCourseID.setText(model.getValueAt(rowIndex, 0).toString());
            jTextFieldCourseName.setText(model.getValueAt(rowIndex, 1).toString());
            jCheckBoxCourseActive.setSelected(false);
            if(model.getValueAt(rowIndex, 2).toString().equals("Open")){
                jCheckBoxCourseActive.setSelected(true);
            }else{
                jCheckBoxCourseActive.setSelected(false);
            }
            int credit = Integer.parseInt(model.getValueAt(rowIndex, 3).toString());
            jComboBoxCredit.getModel().setSelectedItem(credit);
            jComboBoxArea.getModel().setSelectedItem(model.getValueAt(rowIndex, 4).toString());
            jComboBoxDepartment.getModel().setSelectedItem(model.getValueAt(rowIndex, 5).toString());
            jTextFieldPrerequirement.setText(model.getValueAt(rowIndex, 6).toString());
            jTexCourseDescription.setText(model.getValueAt(rowIndex, 7).toString());
        }
    }//GEN-LAST:event_jTable1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageCourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageCourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageCourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageCourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ManageCourseForm st = new ManageCourseForm();
                st.middleScreen();
                st.setVisible(true);
            }
        });
    }
    
    private void middleScreen(){
        double width = Toolkit.getDefaultToolkit().getScreenSize().getWidth();
        double height = Toolkit.getDefaultToolkit().getScreenSize().getHeight();
        this.setLocation( (int) (width - this.getWidth()) / 2,(int) (height - this.getHeight()) / 2);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCosRemove;
    private javax.swing.JButton jButtonCourseAdd;
    private javax.swing.JButton jButtonDepSearch;
    private javax.swing.JButton jButtonManageCourse;
    private javax.swing.JButton jButtonManageFrist;
    private javax.swing.JButton jButtonManageLast;
    private javax.swing.JButton jButtonManageNext;
    private javax.swing.JButton jButtonManagePre;
    private static javax.swing.JCheckBox jCheckBoxCourseActive;
    private static javax.swing.JComboBox jComboBoxArea;
    private static javax.swing.JComboBox jComboBoxCredit;
    private static javax.swing.JComboBox jComboBoxDepartment;
    private static javax.swing.JComboBox jComboBoxKeyArea;
    private static javax.swing.JComboBox jComboBoxKeyDepart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelDepID;
    private javax.swing.JLabel jLabelFirstName;
    private javax.swing.JLabel jLabelLastName1;
    private javax.swing.JLabel jLabelLastName2;
    private javax.swing.JLabel jLabelLastName3;
    private javax.swing.JLabel jLabelLeader;
    private javax.swing.JLabel jLabelLeader1;
    private javax.swing.JLabel jLabelPhone;
    private javax.swing.JLabel jLabelPhone1;
    private javax.swing.JLabel jLabelStuID;
    private javax.swing.JLabel jLabelStuID2;
    private static javax.swing.JLabel jLabelTotalNumPag;
    private javax.swing.JLabel jLabelTotalNumPag1;
    private javax.swing.JLabel jLabelmRe;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPanelAddress;
    public static javax.swing.JTable jTable1;
    private static javax.swing.JTextArea jTexCourseDescription;
    private static javax.swing.JTextField jTextFieldCourseID;
    private static javax.swing.JTextField jTextFieldCourseName;
    private static javax.swing.JTextField jTextFieldKeyword;
    private static javax.swing.JTextField jTextFieldPage;
    private static javax.swing.JTextField jTextFieldPrerequirement;
    public static javax.swing.JTextField jTextFieldRecord;
    // End of variables declaration//GEN-END:variables
    private static int tablePages = 1;
    private static int tableNumOfRecords = 10;
    private static int rowIndex = 0;
    private static DefaultTableModel model = null;
}
