/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jnflsicUI;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jnflsicDataProcess.StuTable;
import jnflsicDataProcess.Student;

/**
 *
 * @author shen
 */
public class ManageStudentForm extends javax.swing.JFrame {
    //StuTable fillT = new StuTable();
    public ManageStudentForm() {
        initComponents();
        ButtonGroup bg = new ButtonGroup();
        bg.add(jRadioButtonMan);
        bg.add(jRadioButtonfelmale);
        jRadioButtonMan.setSelected(true);
        int numCol = jTable1.getColumnCount();
        StuTable.fillStudentJtable((DefaultTableModel)jTable1.getModel(), "", 0, numCol, tableNumOfRecords, tablePages);
        //fillT.fillStuJTable(jTable1,valueToSearch, year);
        jLabelTotalNumPag.setText("/"+StuTable.totalPages());
        model = (DefaultTableModel)jTable1.getModel();
        jTable1.setRowHeight(40);
        jTable1.setShowGrid(true);
        jTable1.setGridColor(Color.GRAY);
        jTable1.setSelectionBackground(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelFirstName = new javax.swing.JLabel();
        jLabelLastName = new javax.swing.JLabel();
        jLabelLastName1 = new javax.swing.JLabel();
        jLabelSex = new javax.swing.JLabel();
        jLabelBirthdate = new javax.swing.JLabel();
        jLabelPhone = new javax.swing.JLabel();
        jLabelAddress = new javax.swing.JLabel();
        jTextFieldFirstName = new javax.swing.JTextField();
        jTextFieldMiddleName = new javax.swing.JTextField();
        jTextFieldLastName = new javax.swing.JTextField();
        jRadioButtonMan = new javax.swing.JRadioButton();
        jRadioButtonfelmale = new javax.swing.JRadioButton();
        dateChooserCombo = new datechooser.beans.DateChooserCombo();
        jTextFieldPhone = new javax.swing.JTextField();
        jScrollPanelAddress = new javax.swing.JScrollPane();
        jTextAreaAddress = new javax.swing.JTextArea();
        jButtonManageStudent = new javax.swing.JButton();
        jButtonStuAdd = new javax.swing.JButton();
        jLabelSex1 = new javax.swing.JLabel();
        jComboBoxGrade = new javax.swing.JComboBox();
        jLabelStuID = new javax.swing.JLabel();
        jTextFieldStuID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelBirthdate1 = new javax.swing.JLabel();
        jTextFieldYear = new javax.swing.JTextField();
        jButtonStuRemove = new javax.swing.JButton();
        jTextFieldKeyword = new javax.swing.JTextField();
        jLabelStuID1 = new javax.swing.JLabel();
        jTextFieldEnrollY = new javax.swing.JTextField();
        jLabelStuID2 = new javax.swing.JLabel();
        jLabelStuID3 = new javax.swing.JLabel();
        jButtonStuSearch = new javax.swing.JButton();
        jButtonManageFrist = new javax.swing.JButton();
        jButtonManagePre = new javax.swing.JButton();
        jTextFieldPage = new javax.swing.JTextField();
        jLabelTotalNumPag = new javax.swing.JLabel();
        jLabelTotalNumPag1 = new javax.swing.JLabel();
        jTextFieldRecord = new javax.swing.JTextField();
        jLabelmRe = new javax.swing.JLabel();
        jButtonManageFrist1 = new javax.swing.JButton();
        jButtonManagePre1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Manage Student");

        jLabelFirstName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelFirstName.setText("First Name:");

        jLabelLastName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelLastName.setText("Last Name:");

        jLabelLastName1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelLastName1.setText("Middle Name:");

        jLabelSex.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelSex.setText("Sex:");

        jLabelBirthdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelBirthdate.setText("BirthDate:");

        jLabelPhone.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPhone.setText("Phone:");

        jLabelAddress.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelAddress.setText("Address:");

        jTextFieldFirstName.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N

        jTextFieldMiddleName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextFieldLastName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jRadioButtonMan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButtonMan.setSelected(true);
        jRadioButtonMan.setText("Male");

        jRadioButtonfelmale.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButtonfelmale.setText("Female");

        dateChooserCombo.setCalendarPreferredSize(new java.awt.Dimension(400, 350));
        dateChooserCombo.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.BOLD, 12));
        dateChooserCombo.setNavigateFont(new java.awt.Font("Shonar Bangla", java.awt.Font.PLAIN, 9));

        jTextFieldPhone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPhoneKeyTyped(evt);
            }
        });

        jTextAreaAddress.setColumns(20);
        jTextAreaAddress.setRows(5);
        jScrollPanelAddress.setViewportView(jTextAreaAddress);

        jButtonManageStudent.setText("Update");
        jButtonManageStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageStudentActionPerformed(evt);
            }
        });

        jButtonStuAdd.setText("Add");
        jButtonStuAdd.setToolTipText("");
        jButtonStuAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStuAddActionPerformed(evt);
            }
        });

        jLabelSex1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelSex1.setText("Grade:");

        jComboBoxGrade.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBoxGrade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10", "11", "12" }));

        jLabelStuID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelStuID.setText("Search");

        jTextFieldStuID.setEditable(false);
        jTextFieldStuID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "StudentID", "FirstName", "MiddleName", "LastName", "Sex", "Grade", "BirthDate", "Enrolled Year", "Phone", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabelBirthdate1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelBirthdate1.setText("Enrolled Year:");

        jTextFieldYear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldYearKeyTyped(evt);
            }
        });

        jButtonStuRemove.setText("Remove");
        jButtonStuRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStuRemoveActionPerformed(evt);
            }
        });

        jTextFieldKeyword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabelStuID1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelStuID1.setText("StudentID:");

        jTextFieldEnrollY.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabelStuID2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelStuID2.setText("Keyword:");

        jLabelStuID3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelStuID3.setText("Enrolled Year: ");

        jButtonStuSearch.setText("Search");
        jButtonStuSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStuSearchActionPerformed(evt);
            }
        });

        jButtonManageFrist.setText("First");
        jButtonManageFrist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageFristActionPerformed(evt);
            }
        });

        jButtonManagePre.setText("Previous");
        jButtonManagePre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManagePreActionPerformed(evt);
            }
        });

        jTextFieldPage.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextFieldPage.setText("1");

        jLabelTotalNumPag.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTotalNumPag.setText("/num");

        jLabelTotalNumPag1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTotalNumPag1.setText("Pages");

        jTextFieldRecord.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextFieldRecord.setText("10");

        jLabelmRe.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelmRe.setText("Records/per page");

        jButtonManageFrist1.setText("Next");
        jButtonManageFrist1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageFrist1ActionPerformed(evt);
            }
        });

        jButtonManagePre1.setText("Last");
        jButtonManagePre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManagePre1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabelFirstName))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabelStuID1))
                            .addComponent(jLabelLastName1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelLastName, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                            .addComponent(jTextFieldMiddleName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldFirstName)
                            .addComponent(jTextFieldStuID)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabelSex)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonMan, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jRadioButtonfelmale))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelSex1)
                            .addComponent(jLabelBirthdate)
                            .addComponent(jLabelBirthdate1)
                            .addComponent(jLabelPhone))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPhone)
                            .addComponent(jTextFieldYear)
                            .addComponent(dateChooserCombo, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBoxGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabelAddress)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonStuAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jButtonManageStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonStuRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPanelAddress))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButtonManageFrist, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jButtonManagePre, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldPage, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelTotalNumPag)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelTotalNumPag1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelmRe)
                                .addGap(50, 50, 50)
                                .addComponent(jButtonManageFrist1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonManagePre1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelStuID)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelStuID2)
                                .addGap(31, 31, 31)
                                .addComponent(jTextFieldKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabelStuID3)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldEnrollY, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonStuSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(230, 230, 230))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldStuID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelStuID1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFirstName)
                            .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLastName1)
                            .addComponent(jTextFieldMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelLastName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelSex)
                                    .addComponent(jRadioButtonMan)
                                    .addComponent(jRadioButtonfelmale))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelSex1)
                                    .addComponent(jComboBoxGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dateChooserCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelBirthdate))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelBirthdate1)
                                    .addComponent(jTextFieldYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelPhone)
                                    .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPanelAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelAddress))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(367, 367, 367)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonManageFrist1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonManagePre1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelTotalNumPag)
                                        .addComponent(jLabelTotalNumPag1)
                                        .addComponent(jTextFieldRecord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelmRe))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonManageFrist, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonManagePre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonStuAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonManageStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonStuRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 41, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonStuSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelStuID)
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldEnrollY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelStuID3))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelStuID2)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private static void clear(){
        jTextFieldStuID.setText("");
        jTextFieldFirstName.setText("");
        jTextFieldMiddleName.setText("");
        jTextFieldLastName.setText("");
        jRadioButtonMan.setSelected(true);
        jRadioButtonfelmale.setSelected(false);
        Calendar cal1 = Calendar.getInstance();
        cal1.setTime(new Date());
        dateChooserCombo.setSelectedDate(cal1);
        jTextFieldYear.setText("");
        jTextFieldPhone.setText("");
        jTextAreaAddress.setText("");
        jComboBoxGrade.setSelectedIndex(0);
    }
    
    private void jButtonStuAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStuAddActionPerformed
        AddStudentForm stf = new AddStudentForm();
        stf.setVisible(true);
        stf.pack();
        stf.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonStuAddActionPerformed

    private void jTextFieldPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPhoneKeyTyped
        //allow only numbers
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldPhoneKeyTyped
    
    private boolean verify(){
        if(jTextFieldFirstName.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter First Name");
            jTextFieldFirstName.requestFocus();
            return false;
        }
        if(jTextFieldLastName.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter Last Name");
            jTextFieldLastName.requestFocus();
            return false;
        }
        if(dateChooserCombo.getSelectedDate()==null){
            JOptionPane.showMessageDialog(null, "Please enter select a date");
            dateChooserCombo.requestFocus();
            return false;
        }
        if(jTextFieldYear.getText().equals("")||jTextFieldYear.getText().length()!=4){
            JOptionPane.showMessageDialog(null, "Please enter enroll year");
            jTextFieldYear.requestFocus();
            return false;
        }
        
        Date now = new Date();
        Calendar n = Calendar.getInstance();
        n.setTime(now);
        int nY = n.get(Calendar.YEAR);
        if(nY-Integer.parseInt(jTextFieldYear.getText())<0){
            JOptionPane.showMessageDialog(null, "Please enter corrected enroll year");
            jTextFieldYear.requestFocus();
            return false;
        }
        
        
        if(dateChooserCombo.getSelectedDate().getTime().compareTo(new Date())>0){
            JOptionPane.showMessageDialog(null, "No Student from future are allowed");
            dateChooserCombo.requestFocus();
            return false;
        }
        if(jTextAreaAddress.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter a home address");
            jTextAreaAddress.requestFocus();
            return false;
        }
        return true;
    }
    
    private void jButtonManageStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageStudentActionPerformed
        String fN = jTextFieldFirstName.getText();
        String mN = jTextFieldMiddleName.getText();
        String lN = jTextFieldLastName.getText();
        char sex = 'm';
        if(jRadioButtonfelmale.isSelected()){
            sex = 'f';
        }
        int grade = jComboBoxGrade.getSelectedIndex()+10;
        Calendar bd = dateChooserCombo.getSelectedDate();
        int year = 0;
        if(!jTextFieldYear.getText().equals("")){
            year = Integer.parseInt(jTextFieldYear.getText());
        }
        String pNum = jTextFieldPhone.getText();
        String add = jTextAreaAddress.getText();
        if(!verify()){
            return;
        }
        Student st = new Student(fN,mN,lN,sex,grade,bd,year,pNum,add);
        st.setID(Integer.parseInt(jTextFieldStuID.getText()));
        if(Student.operateData('u', st)){
            resetTable();
            clear();
        }
    }//GEN-LAST:event_jButtonManageStudentActionPerformed

    private void jTextFieldYearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldYearKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldYearKeyTyped

    private void jButtonStuRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStuRemoveActionPerformed
        if(jTextFieldStuID.getText().equals("")){
            return;
        }
        int id = Integer.parseInt(jTextFieldStuID.getText());
        Student st = new Student();
        st.setID(id);
        if(Student.operateData('d', st)){
            resetTable();
            clear();
        }
    }//GEN-LAST:event_jButtonStuRemoveActionPerformed
    
    public static void resetTable(){
        //System.out.println("aha");
        //jTable1 = new javax.swing.JTable();
        clear();
        //jTable1.clearSelection();
        tablePages = Integer.parseInt(jTextFieldPage.getText());
        tableNumOfRecords = Integer.parseInt(jTextFieldRecord.getText());
        //jTable1.setModel(null);
        //System.out.println("BEreset"+jTable1);
        //model = (DefaultTableModel)jTable1.getModel();
        DefaultTableModel dtm2 = (DefaultTableModel)jTable1.getModel();
        dtm2.setDataVector(null, new String [] {
                "StudentID", "FirstName", "MiddleName", "LastName", "Sex", "Grade", "BirthDate", "Enrolled Year", "Phone", "Address"
            });
//        jTable1.setModel(new DefaultTableModel(null,
//            new String [] {
//                "StudentID", "FirstName", "MiddleName", "LastName", "Sex", "Grade", "BirthDate", "Enrolled Year", "Phone", "Address"
//            }));
        String key = jTextFieldKeyword.getText();
        int y = 0;
        if(!jTextFieldEnrollY.getText().equals("")){
            y = Integer.parseInt(jTextFieldEnrollY.getText());
        }
        //System.out.println("reset"+jTable1);
        StuTable.fillStudentJtable(dtm2, key, y, jTable1.getColumnCount(), tableNumOfRecords, tablePages);
        jLabelTotalNumPag.setText("/"+StuTable.totalPages());
    }
    
    private void jButtonStuSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStuSearchActionPerformed
        resetTable();
    }//GEN-LAST:event_jButtonStuSearchActionPerformed

    private void jButtonManageFristActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageFristActionPerformed
        //tablePages = 1;
        jTextFieldPage.setText("1");
        tableNumOfRecords = Integer.parseInt(jTextFieldRecord.getText());
        resetTable();
    }//GEN-LAST:event_jButtonManageFristActionPerformed

    private void jButtonManagePreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManagePreActionPerformed
        int n = Integer.parseInt(jTextFieldPage.getText())-1;
        if(n==0){
            n = 1;
        }
        jTextFieldPage.setText(n+"");
        tableNumOfRecords = Integer.parseInt(jTextFieldRecord.getText());
        //jTextFieldPage.setText(tablePages+"");
        resetTable();
    }//GEN-LAST:event_jButtonManagePreActionPerformed

    private void jButtonManageFrist1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageFrist1ActionPerformed
        int n = Integer.parseInt(jTextFieldPage.getText())+1;
        if(n>Integer.parseInt(jLabelTotalNumPag.getText().substring(1, 2))){
            n = Integer.parseInt(jLabelTotalNumPag.getText().substring(1, 2));
        }
        jTextFieldPage.setText(n+"");
        tableNumOfRecords = Integer.parseInt(jTextFieldRecord.getText());
        //jTextFieldPage.setText(tablePages+"");
        resetTable();
    }//GEN-LAST:event_jButtonManageFrist1ActionPerformed

    private void jButtonManagePre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManagePre1ActionPerformed
        //tablePages = Integer.parseInt(jLabelTotalNumPag.getText().substring(1,2));
                //tablePages = 1;
        jTextFieldPage.setText(jLabelTotalNumPag.getText().substring(1,2));
        tableNumOfRecords = Integer.parseInt(jTextFieldRecord.getText());
        //jTextFieldPage.setText(tablePages+"");
        resetTable();
    }//GEN-LAST:event_jButtonManagePre1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        rowIndex = jTable1.getSelectedRow();
        //System.out.println("select"+jTable1);
       // model = (DefaultTableModel)jTable1.getModel();
        jTextFieldStuID.setText(model.getValueAt(rowIndex, 0).toString());
        //System.out.println(model.getValueAt(rowIndex, 0).toString());
        System.out.println(model.getValueAt(rowIndex, 0).toString());
        //System.out.println("model "+model.toString());
        jTextFieldFirstName.setText(model.getValueAt(rowIndex, 1).toString());
        jTextFieldMiddleName.setText(model.getValueAt(rowIndex, 2).toString());
        jTextFieldLastName.setText(model.getValueAt(rowIndex, 3).toString());
        if(model.getValueAt(rowIndex, 4).toString().equals("m")){
            jRadioButtonMan.setSelected(true);
        }else{
            jRadioButtonfelmale.setSelected(false);
        }
        String g = model.getValueAt(rowIndex, 5).toString();
        jComboBoxGrade.setSelectedIndex(Integer.parseInt(g)%10);
        //System.out.println(model.getValueAt(rowIndex, 6));
        String d = model.getValueAt(rowIndex, 6).toString();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        try {
            Date date = sdf.parse(d);
            Calendar calendar = Calendar.getInstance();
            calendar.setTime(date);
            dateChooserCombo.setSelectedDate(calendar);
        } catch (ParseException ex) {
            Logger.getLogger(ManageStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextFieldYear.setText(model.getValueAt(rowIndex, 7).toString());
        jTextFieldPhone.setText(model.getValueAt(rowIndex, 8).toString());
        jTextAreaAddress.setText(model.getValueAt(rowIndex, 9).toString());
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_UP || evt.getKeyCode()==KeyEvent.VK_DOWN){
            rowIndex = jTable1.getSelectedRow();
           // model = (DefaultTableModel)jTable1.getModel();
            jTextFieldStuID.setText(model.getValueAt(rowIndex, 0).toString());
            jTextFieldFirstName.setText(model.getValueAt(rowIndex, 1).toString());
            jTextFieldMiddleName.setText(model.getValueAt(rowIndex, 2).toString());
            jTextFieldLastName.setText(model.getValueAt(rowIndex, 3).toString());
            if(model.getValueAt(rowIndex, 4).toString()=="m"){
                jRadioButtonMan.setSelected(true);
            }else{
                jRadioButtonfelmale.setSelected(false);
            }
            String g = model.getValueAt(rowIndex, 5).toString();
            jComboBoxGrade.setSelectedIndex(Integer.parseInt(g)%10);
            //System.out.println(model.getValueAt(rowIndex, 6));
            String d = model.getValueAt(rowIndex, 6).toString();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            try {
                Date date = sdf.parse(d);
                Calendar calendar = Calendar.getInstance();
                calendar.setTime(date);
                dateChooserCombo.setSelectedDate(calendar);
            } catch (ParseException ex) {
                Logger.getLogger(ManageStudentForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            jTextFieldYear.setText(model.getValueAt(rowIndex, 7).toString());
            jTextFieldPhone.setText(model.getValueAt(rowIndex, 8).toString());
            jTextAreaAddress.setText(model.getValueAt(rowIndex, 9).toString());
        }
    }//GEN-LAST:event_jTable1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ManageStudentForm st = new ManageStudentForm();
                st.middleScreen();
                st.setVisible(true);
            }
        });
    }
    
    private void middleScreen(){
        double width = Toolkit.getDefaultToolkit().getScreenSize().getWidth();
        double height = Toolkit.getDefaultToolkit().getScreenSize().getHeight();
        this.setLocation( (int) (width - this.getWidth()) / 2,(int) (height - this.getHeight()) / 2);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static datechooser.beans.DateChooserCombo dateChooserCombo;
    private javax.swing.JButton jButtonManageFrist;
    private javax.swing.JButton jButtonManageFrist1;
    private javax.swing.JButton jButtonManagePre;
    private javax.swing.JButton jButtonManagePre1;
    private javax.swing.JButton jButtonManageStudent;
    private javax.swing.JButton jButtonStuAdd;
    private javax.swing.JButton jButtonStuRemove;
    private javax.swing.JButton jButtonStuSearch;
    private static javax.swing.JComboBox jComboBoxGrade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelBirthdate;
    private javax.swing.JLabel jLabelBirthdate1;
    private javax.swing.JLabel jLabelFirstName;
    private javax.swing.JLabel jLabelLastName;
    private javax.swing.JLabel jLabelLastName1;
    private javax.swing.JLabel jLabelPhone;
    private javax.swing.JLabel jLabelSex;
    private javax.swing.JLabel jLabelSex1;
    private javax.swing.JLabel jLabelStuID;
    private javax.swing.JLabel jLabelStuID1;
    private javax.swing.JLabel jLabelStuID2;
    private javax.swing.JLabel jLabelStuID3;
    private static javax.swing.JLabel jLabelTotalNumPag;
    private javax.swing.JLabel jLabelTotalNumPag1;
    private javax.swing.JLabel jLabelmRe;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JRadioButton jRadioButtonMan;
    private static javax.swing.JRadioButton jRadioButtonfelmale;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPanelAddress;
    public static javax.swing.JTable jTable1;
    private static javax.swing.JTextArea jTextAreaAddress;
    private static javax.swing.JTextField jTextFieldEnrollY;
    private static javax.swing.JTextField jTextFieldFirstName;
    private static javax.swing.JTextField jTextFieldKeyword;
    private static javax.swing.JTextField jTextFieldLastName;
    private static javax.swing.JTextField jTextFieldMiddleName;
    private static javax.swing.JTextField jTextFieldPage;
    private static javax.swing.JTextField jTextFieldPhone;
    public static javax.swing.JTextField jTextFieldRecord;
    private static javax.swing.JTextField jTextFieldStuID;
    private static javax.swing.JTextField jTextFieldYear;
    // End of variables declaration//GEN-END:variables
    private static int tablePages = 1;
    private static int tableNumOfRecords = 10;
    private static int rowIndex = 0;
    private static DefaultTableModel model = null;
}
